using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using SlaveSplit.Agents;
using SlaveSplit.Infrastructure;
using SlaveSplit.Models;
using SlaveSplit.Repositories;
using SlaveSplit.Services;
using SlaveSplit.Services.AI;
using SlaveSplit.Services.LocalLlm;

namespace SlaveSplit.AgentTests
{
    public sealed class AgentScenarioTestRunner
    {
        public LocalAiPreflightResult LastPreflight { get; private set; }
        public async Task<IList<AgentTestResult>> RunAsync(IEnumerable<AgentTestScenario> scenarios)
        {
            List<AgentTestScenario> selected=scenarios.ToList(); if(selected.Any(x=>x.Mode==AgentTestMode.LocalLlm)) LastPreflight=await RunPreflightAsync(); List<AgentTestResult> output = new List<AgentTestResult>(); foreach (AgentTestScenario scenario in selected) { if(scenario.Mode==AgentTestMode.LocalLlm&&(LastPreflight==null||!LastPreflight.Passed)){foreach(AgentTestStep step in scenario.Steps)output.Add(new AgentTestResult{Status="SKIPPED_LOCAL_LLM_UNAVAILABLE",Group=scenario.Group,Scenario=scenario.Name,ScenarioId=scenario.Id,Input=step.Input,Expected=Describe(step),Actual=LastPreflight==null?"Preflight missing":LastPreflight.FailureReason,Source="SKIPPED",Mode=scenario.Mode,LlmFailureKind=LastPreflight==null?"SERVICE_NOT_INJECTED":LastPreflight.FailureReason});continue;} output.AddRange(await RunScenarioAsync(scenario)); } return output;
        }
        public async Task<LocalAiPreflightResult> RunPreflightAsync(){LocalLlmSettings settings=LocalLlmSettings.Load();LocalAiPreflightResult p=new LocalAiPreflightResult{Enabled=settings.Enabled,Endpoint=settings.Endpoint,Model=settings.EffectiveModel,ServiceType=typeof(GraniteOllamaService).Name,FailureReason=settings.Enabled?"NONE":LocalAiFailureKind.Disabled};if(!settings.Enabled)return p;ILocalLlmService service=new GraniteOllamaService(settings.Endpoint,TimeSpan.FromSeconds(Math.Max(45,settings.TimeoutSeconds)));LocalAiAvailability available=await service.CheckAvailabilityAsync(settings.EffectiveModel,CancellationToken.None);p.Connected=available.OllamaConnected;p.ModelFound=available.Online;if(!available.Online){p.FailureReason=available.FailureKind??LocalAiFailureKind.RequestError;return p;}LocalLlmResponse generated=await service.ParseAsync(new LocalLlmRequest{Input="업무 보여줘",CandidateContext="",Model=settings.EffectiveModel},CancellationToken.None);p.GenerateSuccess=generated.Success&&generated.SchemaSuccess;p.GenerateLatencyMs=generated.LatencyMs;p.RawOutput=generated.RawOutput;p.FailureReason=p.GenerateSuccess?"NONE":generated.FailureKind??LocalAiFailureKind.RequestError;return p;}
        private async Task<IList<AgentTestResult>> RunScenarioAsync(AgentTestScenario scenario)
        {
            string reportedGroup=scenario.Group;if(reportedGroup=="Task-029"||reportedGroup=="Task-030"||reportedGroup=="Task-031")scenario.Group="Task-028";
            List<AgentTestResult> output = new List<AgentTestResult>(); AgentTestClock clock = new AgentTestClock(); InMemoryTaskRepository repository = new InMemoryTaskRepository(); WorkspaceService workspaceService=null; ITaskRepository executionRepository=repository;if(scenario.Group=="Task-028"){workspaceService=new WorkspaceService(new[]{new GitHubWorkspace{Id="workspace-a",DisplayName="Workspace-A",Owner="test",Repository="A",CredentialProfileId=WorkspaceService.DefaultCredentialId,IsEnabled=true},new GitHubWorkspace{Id="workspace-b",DisplayName="Workspace-B",Owner="test",Repository="B",CredentialProfileId=WorkspaceService.DefaultCredentialId,IsEnabled=true}},"workspace-a");executionRepository=new WorkspaceTaskRepository(repository,workspaceService);} TaskService tasks = new TaskService(executionRepository, clock);TaskService auditTasks=new TaskService(repository,clock); string logPath = Path.Combine(Path.GetTempPath(), "SlaveSplit", "AgentTests"); AgentLogger logger = new AgentLogger(logPath); ConversationContext context = new ConversationContext(); AiProviderOptions options = new AiProviderOptions(); AiProviderManager providers = new AiProviderManager(options, new MockAiProvider(), new CompanyAiProvider(options, new EnvironmentCredentialProvider("SLAVESPLIT_TEST_UNUSED"))); RuleBasedAgentService rule = new RuleBasedAgentService(tasks, context, clock, logger, new DailySummaryService(tasks, clock)); string[] names = { "create_task","get_today_tasks","get_recent_tasks","search_tasks","get_task","start_task","complete_task","reopen_task","block_task","add_task_memo","update_task_description","update_task_due_date","get_task_github_status","get_recent_history","delete_task","delete_tasks" }; AgentToolRegistry registry = new AgentToolRegistry(names.Select(x => (IAgentTool)new WorkTaskAgentTool(x, tasks, null, null, clock))); LocalLlmSettings llmSettings = LocalLlmSettings.Load(); int llmTimeout=Math.Max(45,llmSettings.TimeoutSeconds); ILocalLlmService llm = new GraniteOllamaService(llmSettings.Endpoint, TimeSpan.FromSeconds(llmTimeout)); AgentConversationService agent = new AgentConversationService(providers, new AiContextBuilder(tasks, clock, options, PromptLoader.LoadSlaveAgentPrompt()), new AgentToolExecutor(registry, context, logger), tasks, context, rule, options, logger, clock, llm, true, llmTimeout,workspaceService);
            scenario.Group=reportedGroup;registry.Register(new WorkTaskAgentTool("update_task_priority",tasks,null,null,clock));registry.Register(new WorkTaskAgentTool("update_task_time",tasks,null,null,clock));registry.Register(new WorkTaskAgentTool("update_task_reminder",tasks,null,null,clock));registry.Register(new WorkTaskAgentTool("work_briefing",tasks,null,null,clock));int fixtureOrder = 0; foreach (AgentTestFixture fixture in scenario.Fixtures) { DateTime now = clock.Now.AddMinutes(-fixtureOrder++); WorkTask item = new WorkTask { Id=Guid.NewGuid(),Title=fixture.Title,Description="",Category="TEST",Priority=fixture.Priority,Status=fixture.Status,Source=TaskSource.Local,WorkspaceId=fixture.WorkspaceId,CreatedAt=now,UpdatedAt=now,DueDate=fixture.NoDueDate?(DateTimeOffset?)null:clock.Now.Date.AddDays(fixture.DueOffsetDays),DueTime=fixture.DueTime,ReminderEnabled=fixture.ReminderEnabled,ReminderOffsetMinutes=fixture.ReminderOffsetMinutes,CompletedAt=fixture.CompletedOffsetDays.HasValue ? (DateTimeOffset?)clock.Now.Date.AddDays(fixture.CompletedOffsetDays.Value).AddHours(12) : null }; await repository.AddAsync(item); }
            for (int i=0;i<scenario.Steps.Count;i++) output.Add(await RunStepAsync(scenario, i, scenario.Steps[i], agent, auditTasks,workspaceService)); return output;
        }
        private static async Task<AgentTestResult> RunStepAsync(AgentTestScenario scenario,int index,AgentTestStep step,AgentConversationService agent,TaskService tasks,WorkspaceService workspaces=null)
        {
            IReadOnlyList<WorkTask> before = await tasks.GetAllAsync(); Dictionary<Guid,string> snapshot = before.ToDictionary(x=>x.Id,Fingerprint); Dictionary<Guid,DateTimeOffset> createdSnapshot=before.ToDictionary(x=>x.Id,x=>x.CreatedAt); Dictionary<Guid,DateTimeOffset?> completedSnapshot=before.ToDictionary(x=>x.Id,x=>x.CompletedAt); Stopwatch watch=Stopwatch.StartNew(); Task<AgentResponse> work=agent.ProcessAsync(new AgentRequest{Message=step.Input,CreatedAt=DateTime.Now,ConversationMessages=new Message[0]}); int timeout=scenario.Mode==AgentTestMode.LocalLlm?Math.Max(45,step.TimeoutSeconds):step.TimeoutSeconds; Task finished=await Task.WhenAny(work,Task.Delay(TimeSpan.FromSeconds(timeout))); AgentResponse response=finished==work?await work:null; watch.Stop(); IReadOnlyList<WorkTask> after=await tasks.GetAllAsync(); int mutations=MutationCount(snapshot,after); List<string> failures=new List<string>(); string message=response==null?"TIMEOUT":response.Message??"";
            if(response==null) failures.Add("Timeout"); else if(response.Success!=step.ExpectSuccess) failures.Add("Success expected="+step.ExpectSuccess+" actual="+response.Success);
            foreach(string value in Split(step.ExpectedContains)) if(message.IndexOf(value,StringComparison.OrdinalIgnoreCase)<0) failures.Add("Missing: "+value);
            foreach(string value in Split(step.ExpectedNotContains)) if(message.IndexOf(value,StringComparison.OrdinalIgnoreCase)>=0) failures.Add("Forbidden: "+value);
            int previous=-1;foreach(string value in Split(step.ExpectedOrder)){int position=message.IndexOf(value,StringComparison.OrdinalIgnoreCase);if(position<0||position<=previous)failures.Add("Order expected: "+step.ExpectedOrder);previous=position;}
            if(step.ExpectedMutationCount.HasValue&&mutations!=step.ExpectedMutationCount.Value) failures.Add("Mutation expected="+step.ExpectedMutationCount+" actual="+mutations);
            if(!string.IsNullOrWhiteSpace(step.ExpectedTitle)&&!after.Any(x=>x.Title==step.ExpectedTitle)) failures.Add("Title not found: "+step.ExpectedTitle);
            if(!string.IsNullOrWhiteSpace(step.ExpectedDescription)){WorkTask described=!string.IsNullOrWhiteSpace(step.ExpectedTitle)?after.FirstOrDefault(x=>x.Title==step.ExpectedTitle):after.FirstOrDefault(x=>!snapshot.ContainsKey(x.Id)||snapshot[x.Id]!=Fingerprint(x));if(described==null||described.Description!=step.ExpectedDescription)failures.Add("Description expected="+step.ExpectedDescription+" actual="+(described==null?"missing":described.Description));}
            if(step.ExpectedStatus.HasValue){IEnumerable<WorkTask> scope=!string.IsNullOrWhiteSpace(step.ExpectedTitle)?after.Where(x=>x.Title==step.ExpectedTitle):after.Where(x=>!before.Any(b=>b.Id==x.Id)||snapshot.ContainsKey(x.Id)&&snapshot[x.Id]!=Fingerprint(x));if(!scope.Any(x=>x.Status==step.ExpectedStatus.Value)) failures.Add("Status not found: "+step.ExpectedStatus);}
            foreach(string expected in Split(step.ExpectedTaskStates)){string[] pair=expected.Split('=');WorkTask task=pair.Length==2?after.FirstOrDefault(x=>x.Title==pair[0]):null;WorkTaskStatus status;if(task==null||!Enum.TryParse(pair[1],true,out status)||task.Status!=status)failures.Add("Task state expected="+expected+" actual="+(task==null?"missing":task.Status.ToString()));}
            foreach(string expected in Split(step.ExpectedCompletedAt)){string[] pair=expected.Split('=');WorkTask task=pair.Length==2?after.FirstOrDefault(x=>x.Title==pair[0]):null;bool shouldSet=pair.Length==2&&pair[1].Equals("set",StringComparison.OrdinalIgnoreCase);if(task==null||task.CompletedAt.HasValue!=shouldSet)failures.Add("CompletedAt expected="+expected+" actual="+(task==null?"missing":task.CompletedAt.HasValue?"set":"null"));}
            foreach(string expected in Split(step.ExpectedDueDates)){string[] pair=expected.Split('=');WorkTask task=pair.Length==2?after.FirstOrDefault(x=>x.Title==pair[0]):null;int offset;bool wantsNull=pair.Length==2&&pair[1].Equals("null",StringComparison.OrdinalIgnoreCase);if(task==null||(wantsNull?task.DueDate.HasValue:!int.TryParse(pair.Length==2?pair[1]:"",out offset)||!task.DueDate.HasValue||task.DueDate.Value.Date!=new DateTime(2026,9,1).AddDays(offset).Date))failures.Add("DueDate expected="+expected+" actual="+(task==null?"missing":task.DueDate.HasValue?task.DueDate.Value.ToString("yyyy-MM-dd"):"null"));}
            foreach(string expected in Split(step.ExpectedPriorities)){string[] pair=expected.Split('=');WorkTask task=pair.Length==2?after.FirstOrDefault(x=>x.Title==pair[0]):null;TaskPriority priority;if(task==null||!Enum.TryParse(pair.Length==2?pair[1]:"",true,out priority)||task.Priority!=priority)failures.Add("Priority expected="+expected+" actual="+(task==null?"missing":task.Priority.ToString()));}
            foreach(string expected in Split(step.ExpectedDueTimes)){string[] pair=expected.Split('=');WorkTask task=pair.Length==2?after.FirstOrDefault(x=>x.Title==pair[0]):null;TimeSpan parsed;bool wantsNull=pair.Length==2&&pair[1].Equals("null",StringComparison.OrdinalIgnoreCase);if(task==null||(wantsNull?task.DueTime.HasValue:!TimeSpan.TryParse(pair.Length==2?pair[1]:"",out parsed)||task.DueTime!=parsed))failures.Add("DueTime expected="+expected+" actual="+(task==null?"missing":task.DueTime.HasValue?task.DueTime.Value.ToString(@"hh\:mm"):"null"));}
            foreach(string expected in Split(step.ExpectedReminders)){string[] parts=expected.Split('=');WorkTask task=parts.Length==2?after.FirstOrDefault(x=>x.Title==parts[0]):null;string[] values=parts.Length==2?parts[1].Split(','):new string[0];bool enabled;int offset;if(task==null||values.Length!=2||!bool.TryParse(values[0],out enabled)||task.ReminderEnabled!=enabled||!int.TryParse(values[1],out offset)||(task.ReminderOffsetMinutes??0)!=offset)failures.Add("Reminder expected="+expected+" actual="+(task==null?"missing":task.ReminderEnabled+","+(task.ReminderOffsetMinutes??0)));}
            if(step.PreserveCreatedAt&&after.Any(x=>createdSnapshot.ContainsKey(x.Id)&&x.CreatedAt!=createdSnapshot[x.Id]))failures.Add("CreatedAt changed");
            if(step.PreserveCompletedAt&&after.Any(x=>completedSnapshot.ContainsKey(x.Id)&&x.CompletedAt!=completedSnapshot[x.Id]))failures.Add("CompletedAt changed");
            if(workspaces!=null&&!string.IsNullOrWhiteSpace(step.ExpectedActiveWorkspace)&&workspaces.ActiveWorkspace.Id!=step.ExpectedActiveWorkspace)failures.Add("ActiveWorkspace expected="+step.ExpectedActiveWorkspace+" actual="+workspaces.ActiveWorkspace.Id);
            if(response!=null&&!string.IsNullOrWhiteSpace(step.ExpectedSource)&&response.InterpreterSource!=step.ExpectedSource) failures.Add("Source expected="+step.ExpectedSource+" actual="+(response.InterpreterSource??"null")); if(response!=null&&step.ExpectedFallback.HasValue&&response.FallbackCalled!=step.ExpectedFallback.Value) failures.Add("Fallback expected="+step.ExpectedFallback+" actual="+response.FallbackCalled);
            List<WorkTask> affected=after.Where(x=>!snapshot.ContainsKey(x.Id)||snapshot[x.Id]!=Fingerprint(x)).ToList();string affectedText=string.Join(", ",affected.Select(x=>x.Title));bool targetMismatch=!string.IsNullOrWhiteSpace(step.ExpectedAffectedTasks)&&!SameSet(Split(step.ExpectedAffectedTasks),affected.Select(x=>x.Title));if(targetMismatch)failures.Add("Affected expected="+step.ExpectedAffectedTasks+" actual="+affectedText);bool wrong=step.ExpectedMutationCount.HasValue&&mutations!=step.ExpectedMutationCount.Value||targetMismatch;return new AgentTestResult{Status=failures.Count==0?"PASS":"FAIL",Group=scenario.Group,Scenario=scenario.Name,ScenarioId=scenario.Id,Step=index+1,Input=step.Input,Expected=Describe(step),Actual=message,Source=response==null?"TIMEOUT":response.InterpreterSource??"PARSER",LatencyMs=watch.ElapsedMilliseconds,FailureReason=string.Join("; ",failures),Mode=scenario.Mode,FallbackRequested=response!=null&&response.FallbackCalled,LlmCalled=response!=null&&response.LlmCalled,LlmSuccess=response!=null&&response.LlmSuccess,LlmFailureKind=response==null?"TIMEOUT":response.LlmFailureKind,LlmRawOutput=response==null?null:response.LlmRawOutput,ExpectedMutationCount=step.ExpectedMutationCount,ActualMutationCount=mutations,AffectedTasks=affectedText,BeforeState=string.Join("; ",before.Select(x=>x.Title+"="+x.Status)),AfterState=string.Join("; ",after.Select(x=>x.Title+"="+x.Status)),WrongMutation=wrong};
        }
        private static int MutationCount(IDictionary<Guid,string> before,IReadOnlyList<WorkTask> after){int changed=after.Count(x=>!before.ContainsKey(x.Id)||before[x.Id]!=Fingerprint(x));changed+=before.Keys.Count(id=>!after.Any(x=>x.Id==id));return changed;}
        private static string Fingerprint(WorkTask x){return x.Title+"|"+x.Description+"|"+x.Status+"|"+x.Priority+"|"+(x.DueDate.HasValue?x.DueDate.Value.ToString("o"):"")+"|"+(x.DueTime.HasValue?x.DueTime.Value.ToString():"")+"|"+x.ReminderEnabled+"|"+(x.ReminderOffsetMinutes.HasValue?x.ReminderOffsetMinutes.Value.ToString():"")+"|"+(x.CompletedAt.HasValue?x.CompletedAt.Value.ToString("o"):"");}
        private static IEnumerable<string> Split(string value){return (value??"").Split(new[]{'|'},StringSplitOptions.RemoveEmptyEntries);}
        private static bool SameSet(IEnumerable<string> expected,IEnumerable<string> actual){return expected.OrderBy(x=>x).SequenceEqual(actual.OrderBy(x=>x));}
        private static string Describe(AgentTestStep x){return "contains="+(x.ExpectedContains??"-")+", not="+(x.ExpectedNotContains??"-")+", mutations="+(x.ExpectedMutationCount.HasValue?x.ExpectedMutationCount.ToString():"-")+(x.ExpectedStatus.HasValue?", status="+x.ExpectedStatus:"")+(string.IsNullOrWhiteSpace(x.ExpectedTaskStates)?"":", states="+x.ExpectedTaskStates);}
    }
}
