using System;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
namespace SlaveSplit.Services.GitHub
{
    public sealed class GitHubService : IGitHubService
    {
        private readonly GitHubClient client; private readonly IGitHubCredentialProvider credentials; private readonly GitHubStatusService status;
        public GitHubService(GitHubClient client, IGitHubCredentialProvider credentials, GitHubStatusService status = null) { this.client = client; this.credentials = credentials; this.status = status ?? new GitHubStatusService(); }
        public Task<GitHubConnectionResult> TestConnectionAsync(GitHubSettings settings, CancellationToken cancellationToken) { return GetRepositoryAsync(settings, cancellationToken); }
        public async Task<GitHubConnectionResult> GetRepositoryAsync(GitHubSettings settings, CancellationToken cancellationToken)
        {
            Stopwatch watch = Stopwatch.StartNew(); if (settings == null || string.IsNullOrWhiteSpace(settings.Owner) || string.IsNullOrWhiteSpace(settings.Repository)) return Result(false, null, "GitHub is not configured.", GitHubConnectionStatus.NotConfigured, watch.ElapsedMilliseconds);
            status.SetStatus(GitHubConnectionStatus.Connecting); try { string token = credentials.GetToken(); using (CancellationTokenSource timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken)) { timeout.CancelAfter(TimeSpan.FromSeconds(Math.Max(1, settings.TimeoutSeconds))); using (HttpResponseMessage response = await client.GetRepositoryAsync(settings.Owner.Trim(), settings.Repository.Trim(), token, timeout.Token)) { string json = await response.Content.ReadAsStringAsync(); if (response.StatusCode == HttpStatusCode.Unauthorized) return Finish(Result(false, response.StatusCode, "Authentication failed. Check your GitHub token.", GitHubConnectionStatus.AuthenticationFailed, watch.ElapsedMilliseconds)); if (response.StatusCode == HttpStatusCode.Forbidden) return Finish(Result(false, response.StatusCode, "GitHub access was forbidden or rate limited.", GitHubConnectionStatus.Error, watch.ElapsedMilliseconds)); if (response.StatusCode == HttpStatusCode.NotFound) return Finish(Result(false, response.StatusCode, string.IsNullOrWhiteSpace(token) ? "Repository not found. Enter a token if the repository is private." : "Repository not found or the token cannot access it. Check Owner, Repository, and token permissions.", GitHubConnectionStatus.RepositoryNotFound, watch.ElapsedMilliseconds)); if (!response.IsSuccessStatusCode) return Finish(Result(false, response.StatusCode, "GitHub connection failed.", GitHubConnectionStatus.Error, watch.ElapsedMilliseconds)); GitHubRepositoryDto dto = JsonConvert.DeserializeObject<GitHubRepositoryDto>(json); if (dto == null) return Finish(Result(false, response.StatusCode, "GitHub returned an invalid repository response.", GitHubConnectionStatus.Error, watch.ElapsedMilliseconds)); return Finish(new GitHubConnectionResult { Success = true, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.Connected, Message = "Connected", ElapsedMilliseconds = watch.ElapsedMilliseconds, Repository = new GitHubRepositoryInfo { Id = dto.Id, Name = dto.Name, FullName = dto.FullName, Description = dto.Description, Private = dto.Private, DefaultBranch = dto.DefaultBranch, HtmlUrl = dto.HtmlUrl } }); } } }
            catch (OperationCanceledException) { return Finish(Result(false, null, cancellationToken.IsCancellationRequested ? "GitHub connection cancelled." : "GitHub connection timed out.", GitHubConnectionStatus.Disconnected, watch.ElapsedMilliseconds)); }
            catch (HttpRequestException) { return Finish(Result(false, null, "GitHub connection failed. Check the network.", GitHubConnectionStatus.Disconnected, watch.ElapsedMilliseconds)); }
            catch { return Finish(Result(false, null, "GitHub connection failed.", GitHubConnectionStatus.Error, watch.ElapsedMilliseconds)); }
        }
        public async Task<GitHubIssuesResult> GetIssuesAsync(GitHubSettings settings, GitHubIssueQuery query, CancellationToken cancellationToken)
        {
            Stopwatch watch = Stopwatch.StartNew(); query = query ?? new GitHubIssueQuery(); if (!Configured(settings)) return new GitHubIssuesResult { Success = false, Status = GitHubConnectionStatus.NotConfigured, Message = "GitHub isn't connected." };
            status.SetStatus(GitHubConnectionStatus.Connecting); try { using (CancellationTokenSource timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken)) { timeout.CancelAfter(TimeSpan.FromSeconds(Math.Max(1, settings.TimeoutSeconds))); using (HttpResponseMessage response = await client.GetIssuesAsync(settings.Owner.Trim(), settings.Repository.Trim(), query, credentials.GetToken(), timeout.Token)) { string json = await response.Content.ReadAsStringAsync(); GitHubIssuesResult error = IssueError(response.StatusCode, watch.ElapsedMilliseconds); if (error != null) return Finish(error); List<GitHubIssueDto> dtos; try { dtos = JsonConvert.DeserializeObject<List<GitHubIssueDto>>(json) ?? new List<GitHubIssueDto>(); } catch { return Finish(new GitHubIssuesResult { Success = false, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.Error, Message = "GitHub returned an invalid issue response.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); } List<GitHubIssueInfo> issues = new List<GitHubIssueInfo>(); foreach (GitHubIssueDto dto in dtos) { if (dto == null || dto.PullRequest != null) continue; try { issues.Add(MapIssue(dto)); } catch { } } return Finish(new GitHubIssuesResult { Success = true, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.Connected, Message = "Loaded " + issues.Count + " issues.", ElapsedMilliseconds = watch.ElapsedMilliseconds, Issues = issues, Page = query.Page, HasNextPage = dtos.Count >= Math.Max(1, Math.Min(100, query.PerPage)) }); } } }
            catch (OperationCanceledException) { return Finish(new GitHubIssuesResult { Success = false, Status = GitHubConnectionStatus.Disconnected, Message = cancellationToken.IsCancellationRequested ? "GitHub request cancelled." : "GitHub connection timed out.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); } catch (HttpRequestException) { return Finish(new GitHubIssuesResult { Success = false, Status = GitHubConnectionStatus.Disconnected, Message = "GitHub is currently unavailable. Your local tasks are still available.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); } catch { return Finish(new GitHubIssuesResult { Success = false, Status = GitHubConnectionStatus.Error, Message = "GitHub issue loading failed.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); }
        }
        public async Task<GitHubIssueResult> GetIssueAsync(GitHubSettings settings, int issueNumber, CancellationToken cancellationToken)
        {
            Stopwatch watch = Stopwatch.StartNew(); if (!Configured(settings) || issueNumber <= 0) return new GitHubIssueResult { Success = false, Status = GitHubConnectionStatus.NotConfigured, Message = "GitHub issue is not configured." }; status.SetStatus(GitHubConnectionStatus.Connecting);
            try { using (CancellationTokenSource timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken)) { timeout.CancelAfter(TimeSpan.FromSeconds(Math.Max(1, settings.TimeoutSeconds))); using (HttpResponseMessage response = await client.GetIssueAsync(settings.Owner.Trim(), settings.Repository.Trim(), issueNumber, credentials.GetToken(), timeout.Token)) { string json = await response.Content.ReadAsStringAsync(); GitHubIssuesResult listError = IssueError(response.StatusCode, watch.ElapsedMilliseconds); if (listError != null) { status.SetStatus(listError.Status); return new GitHubIssueResult { Success = false, StatusCode = listError.StatusCode, Status = listError.Status, Message = listError.Message, ElapsedMilliseconds = listError.ElapsedMilliseconds }; } GitHubIssueDto dto; try { dto = JsonConvert.DeserializeObject<GitHubIssueDto>(json); } catch { dto = null; } if (dto == null || dto.PullRequest != null) { status.SetStatus(GitHubConnectionStatus.Error); return new GitHubIssueResult { Success = false, Status = GitHubConnectionStatus.Error, Message = "GitHub returned an invalid issue response.", ElapsedMilliseconds = watch.ElapsedMilliseconds }; } status.SetStatus(GitHubConnectionStatus.Connected); return new GitHubIssueResult { Success = true, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.Connected, Message = "Issue loaded.", ElapsedMilliseconds = watch.ElapsedMilliseconds, Issue = MapIssue(dto) }; } } }
            catch (OperationCanceledException) { status.SetStatus(GitHubConnectionStatus.Disconnected); return new GitHubIssueResult { Success = false, Status = GitHubConnectionStatus.Disconnected, Message = cancellationToken.IsCancellationRequested ? "GitHub request cancelled." : "GitHub connection timed out.", ElapsedMilliseconds = watch.ElapsedMilliseconds }; } catch (HttpRequestException) { status.SetStatus(GitHubConnectionStatus.Disconnected); return new GitHubIssueResult { Success = false, Status = GitHubConnectionStatus.Disconnected, Message = "GitHub is currently unavailable. Your local tasks are still available.", ElapsedMilliseconds = watch.ElapsedMilliseconds }; } catch { status.SetStatus(GitHubConnectionStatus.Error); return new GitHubIssueResult { Success = false, Status = GitHubConnectionStatus.Error, Message = "GitHub issue loading failed.", ElapsedMilliseconds = watch.ElapsedMilliseconds }; }
        }
        public async Task<GitHubIssueResult> CreateIssueAsync(GitHubSettings settings, GitHubCreateIssueRequest request, CancellationToken cancellationToken)
        {
            Stopwatch watch = Stopwatch.StartNew(); if (!Configured(settings) || request == null || string.IsNullOrWhiteSpace(request.Title)) return new GitHubIssueResult { Success = false, Status = GitHubConnectionStatus.NotConfigured, Message = "GitHub issue title and repository are required." }; status.SetStatus(GitHubConnectionStatus.Connecting);
            try { using (CancellationTokenSource timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken)) { timeout.CancelAfter(TimeSpan.FromSeconds(Math.Max(1, settings.TimeoutSeconds))); using (HttpResponseMessage response = await client.CreateIssueAsync(settings.Owner.Trim(), settings.Repository.Trim(), request, credentials.GetToken(), timeout.Token)) { string json = await response.Content.ReadAsStringAsync(); if (response.StatusCode == HttpStatusCode.Unauthorized) return Finish(new GitHubIssueResult { Success = false, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.AuthenticationFailed, Message = "Authentication failed. Check GitHub settings.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); if (response.StatusCode == HttpStatusCode.Forbidden) return Finish(new GitHubIssueResult { Success = false, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.Error, Message = "GitHub issue creation was forbidden. Check token Issues write permission.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); if (response.StatusCode == HttpStatusCode.NotFound) return Finish(new GitHubIssueResult { Success = false, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.RepositoryNotFound, Message = "Repository not found or the token cannot create issues.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); if (response.StatusCode != HttpStatusCode.Created) return Finish(new GitHubIssueResult { Success = false, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.Error, Message = "GitHub issue creation failed.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); GitHubIssueDto dto; try { dto = JsonConvert.DeserializeObject<GitHubIssueDto>(json); } catch { dto = null; } if (dto == null || dto.Number <= 0) return Finish(new GitHubIssueResult { Success = false, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.Error, Message = "GitHub returned an invalid issue response.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); return Finish(new GitHubIssueResult { Success = true, StatusCode = response.StatusCode, Status = GitHubConnectionStatus.Connected, Message = "GitHub Issue #" + dto.Number + " created.", ElapsedMilliseconds = watch.ElapsedMilliseconds, Issue = MapIssue(dto) }); } } }
            catch (OperationCanceledException) { return Finish(new GitHubIssueResult { Success = false, Status = GitHubConnectionStatus.Disconnected, Message = cancellationToken.IsCancellationRequested ? "GitHub request cancelled." : "GitHub connection timed out.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); } catch (HttpRequestException) { return Finish(new GitHubIssueResult { Success = false, Status = GitHubConnectionStatus.Disconnected, Message = "GitHub is currently unavailable. Local task is still available.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); } catch { return Finish(new GitHubIssueResult { Success = false, Status = GitHubConnectionStatus.Error, Message = "GitHub issue creation failed. Local task is still available.", ElapsedMilliseconds = watch.ElapsedMilliseconds }); }
        }
        public Task<GitHubOperationResult> CloseIssueAsync(GitHubSettings settings, int issueNumber, CancellationToken cancellationToken) { return UpdateStateAsync(settings, issueNumber, "closed", cancellationToken); }
        public Task<GitHubOperationResult> ReopenIssueAsync(GitHubSettings settings, int issueNumber, CancellationToken cancellationToken) { return UpdateStateAsync(settings, issueNumber, "open", cancellationToken); }
        public async Task<GitHubOperationResult> AddIssueCommentAsync(GitHubSettings settings, int issueNumber, string body, CancellationToken cancellationToken)
        {
            if (string.IsNullOrWhiteSpace(body)) return Operation(false, null, "Comment is required.", 0); return await SendOperationAsync(settings, issueNumber, delegate(string owner, string repo, string token, CancellationToken ct) { return client.AddIssueCommentAsync(owner, repo, issueNumber, body, token, ct); }, cancellationToken);
        }
        public Task<GitHubOperationResult> UpdateIssueBodyAsync(GitHubSettings settings, int issueNumber, string body, CancellationToken cancellationToken) { return SendOperationAsync(settings, issueNumber, delegate(string owner, string repo, string token, CancellationToken ct) { return client.UpdateIssueBodyAsync(owner, repo, issueNumber, body ?? "", token, ct); }, cancellationToken); }
        private Task<GitHubOperationResult> UpdateStateAsync(GitHubSettings settings, int issueNumber, string stateValue, CancellationToken cancellationToken) { return SendOperationAsync(settings, issueNumber, delegate(string owner, string repo, string token, CancellationToken ct) { return client.UpdateIssueStateAsync(owner, repo, issueNumber, stateValue, token, ct); }, cancellationToken); }
        private async Task<GitHubOperationResult> SendOperationAsync(GitHubSettings settings, int issueNumber, Func<string, string, string, CancellationToken, Task<HttpResponseMessage>> send, CancellationToken cancellationToken)
        {
            Stopwatch watch = Stopwatch.StartNew(); if (!Configured(settings) || issueNumber <= 0) return Operation(false, null, "GitHub issue is not configured.", watch.ElapsedMilliseconds); try { using (CancellationTokenSource timeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken)) { timeout.CancelAfter(TimeSpan.FromSeconds(Math.Max(1, settings.TimeoutSeconds))); using (HttpResponseMessage response = await send(settings.Owner.Trim(), settings.Repository.Trim(), credentials.GetToken(), timeout.Token)) { if (response.IsSuccessStatusCode) return Operation(true, response.StatusCode, "GitHub synchronized.", watch.ElapsedMilliseconds); if (response.StatusCode == HttpStatusCode.Unauthorized) return Operation(false, response.StatusCode, "Authentication failed. Check GitHub settings.", watch.ElapsedMilliseconds); if (response.StatusCode == HttpStatusCode.Forbidden) return Operation(false, response.StatusCode, "GitHub access was forbidden. Check token write permission.", watch.ElapsedMilliseconds); if (response.StatusCode == HttpStatusCode.NotFound) return Operation(false, response.StatusCode, "GitHub Issue not found. Local task remains available.", watch.ElapsedMilliseconds); return Operation(false, response.StatusCode, "GitHub synchronization failed.", watch.ElapsedMilliseconds); } } } catch (OperationCanceledException) { return Operation(false, null, cancellationToken.IsCancellationRequested ? "GitHub request cancelled." : "GitHub connection timed out.", watch.ElapsedMilliseconds); } catch (HttpRequestException) { return Operation(false, null, "GitHub is currently unavailable.", watch.ElapsedMilliseconds); } catch { return Operation(false, null, "GitHub synchronization failed.", watch.ElapsedMilliseconds); }
        }
        private static GitHubOperationResult Operation(bool success, HttpStatusCode? code, string message, long elapsed) { return new GitHubOperationResult { Success = success, StatusCode = code, Message = message, ElapsedMilliseconds = elapsed }; }
        private static bool Configured(GitHubSettings settings) { return settings != null && !string.IsNullOrWhiteSpace(settings.Owner) && !string.IsNullOrWhiteSpace(settings.Repository); }
        private GitHubIssuesResult Finish(GitHubIssuesResult result) { status.SetStatus(result.Status); return result; }
        private GitHubIssueResult Finish(GitHubIssueResult result) { status.SetStatus(result.Status); return result; }
        private static GitHubIssuesResult IssueError(HttpStatusCode code, long elapsed) { if (code == HttpStatusCode.OK) return null; if (code == HttpStatusCode.Unauthorized) return new GitHubIssuesResult { Success = false, StatusCode = code, Status = GitHubConnectionStatus.AuthenticationFailed, Message = "Authentication failed. Check GitHub settings.", ElapsedMilliseconds = elapsed }; if (code == HttpStatusCode.Forbidden) return new GitHubIssuesResult { Success = false, StatusCode = code, Status = GitHubConnectionStatus.Error, Message = "GitHub access was forbidden or rate limited.", ElapsedMilliseconds = elapsed }; if (code == HttpStatusCode.NotFound) return new GitHubIssuesResult { Success = false, StatusCode = code, Status = GitHubConnectionStatus.RepositoryNotFound, Message = "Repository or issue not found.", ElapsedMilliseconds = elapsed }; return new GitHubIssuesResult { Success = false, StatusCode = code, Status = GitHubConnectionStatus.Error, Message = "GitHub issue request failed.", ElapsedMilliseconds = elapsed }; }
        private static GitHubIssueInfo MapIssue(GitHubIssueDto dto) { GitHubIssueInfo issue = new GitHubIssueInfo { Number = dto.Number, NodeId = dto.NodeId, Title = dto.Title ?? "Untitled issue", Body = dto.Body, State = string.Equals(dto.State, "closed", StringComparison.OrdinalIgnoreCase) ? GitHubIssueState.Closed : GitHubIssueState.Open, HtmlUrl = dto.HtmlUrl, CreatedAt = dto.CreatedAt, UpdatedAt = dto.UpdatedAt, ClosedAt = dto.ClosedAt, Author = dto.User == null ? null : new GitHubUserInfo { Login = dto.User.Login, AvatarUrl = dto.User.AvatarUrl } }; foreach (GitHubUserDto user in dto.Assignees ?? new List<GitHubUserDto>()) if (user != null) issue.Assignees.Add(new GitHubUserInfo { Login = user.Login, AvatarUrl = user.AvatarUrl }); foreach (GitHubLabelDto label in dto.Labels ?? new List<GitHubLabelDto>()) if (label != null) issue.Labels.Add(new GitHubLabelInfo { Name = label.Name ?? "label", Description = label.Description, Color = label.Color }); return issue; }
        private GitHubConnectionResult Finish(GitHubConnectionResult result) { status.SetStatus(result.Status); return result; }
        private static GitHubConnectionResult Result(bool success, HttpStatusCode? code, string message, GitHubConnectionStatus state, long elapsed) { return new GitHubConnectionResult { Success = success, StatusCode = code, Message = message, Status = state, ElapsedMilliseconds = elapsed }; }
    }
}
