using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json;
using SlaveSplit.Models;

namespace SlaveSplit.Services.GitHub
{
    public interface IGitHubSyncService
    {
        Task QueueCloseAsync(WorkTask task); Task QueueReopenAsync(WorkTask task); Task QueueCommentAsync(WorkTask task, string comment); Task QueueIssueBodyAsync(WorkTask task, string body); Task QueueProjectStatusAsync(WorkTask task); Task RetryTaskAsync(WorkTask task); Task<int> RetryAllAsync(); Task<int> GetPendingCountAsync(Guid? taskId = null);
    }
    public sealed class GitHubSyncService : IGitHubSyncService
    {
        private readonly TaskService tasks; private readonly IGitHubService github; private readonly IGitHubProjectService projects; private readonly GitHubSettingsService settings; private readonly string path; private readonly SemaphoreSlim gate = new SemaphoreSlim(1, 1);
        public GitHubSyncService(TaskService tasks, IGitHubService github, GitHubSettingsService settings, string directory = null, IGitHubProjectService projects = null) { this.tasks = tasks; this.github = github; this.settings = settings; this.projects = projects; string root = directory ?? Environment.GetEnvironmentVariable("SLAVESPLIT_DATA_DIR") ?? Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "SlaveSplit"); Directory.CreateDirectory(root); path = Path.Combine(root, "github_pending_operations.json"); }
        public Task QueueCloseAsync(WorkTask task) { return QueueAsync(task, GitHubOperationType.CloseIssue, null); }
        public Task QueueReopenAsync(WorkTask task) { return QueueAsync(task, GitHubOperationType.ReopenIssue, null); }
        public Task QueueCommentAsync(WorkTask task, string comment) { return string.IsNullOrWhiteSpace(comment) ? Task.FromResult(0) : QueueAsync(task, GitHubOperationType.AddComment, comment.Trim()); }
        public Task QueueIssueBodyAsync(WorkTask task, string body) { return QueueAsync(task, GitHubOperationType.UpdateIssueBody, body ?? ""); }
        public async Task QueueProjectStatusAsync(WorkTask task) { GitHubSettings value = settings.Load(); if (task == null || projects == null || !value.ProjectSyncEnabled || string.IsNullOrWhiteSpace(value.ProjectId) || string.IsNullOrWhiteSpace(value.StatusFieldId)) return; if (string.IsNullOrWhiteSpace(task.GitHubProjectItemId)) { if (string.IsNullOrWhiteSpace(task.GitHubNodeId)) return; await QueueAsync(task, GitHubOperationType.AddProjectItem, task.GitHubNodeId); if (string.IsNullOrWhiteSpace(task.GitHubProjectItemId)) return; } string option = task.Status == WorkTaskStatus.Done ? value.DoneOptionId : task.Status == WorkTaskStatus.InProgress ? value.InProgressOptionId : task.Status == WorkTaskStatus.Blocked ? value.BlockedOptionId : value.TodoOptionId; if (!string.IsNullOrWhiteSpace(option)) await QueueAsync(task, GitHubOperationType.UpdateProjectStatus, option); }
        private async Task QueueAsync(WorkTask task, GitHubOperationType type, string payload) { int number; if (!Mapped(task, out number)) return; PendingGitHubOperation operation = new PendingGitHubOperation { Id = Guid.NewGuid(), TaskId = task.Id, IssueNumber = number, OperationType = type, Payload = payload, CreatedAt = DateTime.Now }; await gate.WaitAsync(); try { List<PendingGitHubOperation> all = Read(); all.Add(operation); Write(all); } finally { gate.Release(); } if (type == GitHubOperationType.AddProjectItem || type == GitHubOperationType.UpdateProjectStatus) task.GitHubProjectSyncStatus = GitHubSyncStatus.Pending; else task.GitHubSyncStatus = GitHubSyncStatus.Pending; task.LastGitHubSyncError = null; await tasks.SaveIntegrationStateAsync(task); await TryOperationAsync(operation, task); }
        public async Task RetryTaskAsync(WorkTask task) { if (task == null) return; List<PendingGitHubOperation> values = await ReadAsync(); foreach (PendingGitHubOperation operation in values.Where(x => x.TaskId == task.Id).OrderBy(x => x.CreatedAt).ToList()) await TryOperationAsync(operation, task); }
        public async Task<int> RetryAllAsync() { int success = 0; List<PendingGitHubOperation> values = await ReadAsync(); foreach (PendingGitHubOperation operation in values.OrderBy(x => x.CreatedAt).ToList()) { WorkTask task = await tasks.GetByIdAsync(operation.TaskId); if (task != null && await TryOperationAsync(operation, task)) success++; } return success; }
        public async Task<int> GetPendingCountAsync(Guid? taskId = null) { List<PendingGitHubOperation> values = await ReadAsync(); return taskId.HasValue ? values.Count(x => x.TaskId == taskId.Value) : values.Count; }
        private async Task<bool> TryOperationAsync(PendingGitHubOperation operation, WorkTask task)
        {
            bool projectOperation = operation.OperationType == GitHubOperationType.AddProjectItem || operation.OperationType == GitHubOperationType.UpdateProjectStatus; if (projectOperation) task.GitHubProjectSyncStatus = GitHubSyncStatus.Syncing; else task.GitHubSyncStatus = GitHubSyncStatus.Syncing; await tasks.SaveIntegrationStateAsync(task); GitHubSettings current = settings.Load(); GitHubOperationResult result; if (operation.OperationType == GitHubOperationType.CloseIssue) result = await github.CloseIssueAsync(current, operation.IssueNumber, CancellationToken.None); else if (operation.OperationType == GitHubOperationType.ReopenIssue) result = await github.ReopenIssueAsync(current, operation.IssueNumber, CancellationToken.None); else if (operation.OperationType == GitHubOperationType.AddComment) result = await github.AddIssueCommentAsync(current, operation.IssueNumber, operation.Payload, CancellationToken.None); else if (operation.OperationType == GitHubOperationType.UpdateIssueBody) result = await github.UpdateIssueBodyAsync(current, operation.IssueNumber, operation.Payload, CancellationToken.None); else { GitHubProjectItemResult projectResult = operation.OperationType == GitHubOperationType.AddProjectItem ? await projects.AddItemAsync(current.ProjectId, operation.Payload, CancellationToken.None) : await projects.UpdateStatusAsync(current.ProjectId, task.GitHubProjectItemId, current.StatusFieldId, operation.Payload, CancellationToken.None); if (projectResult.Success && operation.OperationType == GitHubOperationType.AddProjectItem) task.GitHubProjectItemId = projectResult.ItemId; result = new GitHubOperationResult { Success = projectResult.Success, Message = projectResult.Message }; }
            if (result.Success) { await RemoveAsync(operation.Id); int remaining = await GetPendingCountAsync(task.Id); if (projectOperation) task.GitHubProjectSyncStatus = GitHubSyncStatus.Synced; else task.GitHubSyncStatus = remaining == 0 ? GitHubSyncStatus.Synced : GitHubSyncStatus.Pending; task.LastGitHubSyncAt = DateTime.Now; task.LastGitHubSyncError = null; await tasks.SaveIntegrationStateAsync(task); await tasks.RecordGitHubSyncAsync(task, OperationText(operation)); return true; }
            operation.RetryCount++; operation.LastAttemptAt = DateTime.Now; operation.LastError = Safe(result.Message); await ReplaceAsync(operation); if (projectOperation) task.GitHubProjectSyncStatus = GitHubSyncStatus.Pending; else task.GitHubSyncStatus = GitHubSyncStatus.Pending; task.LastGitHubSyncError = operation.LastError; await tasks.SaveIntegrationStateAsync(task); return false;
        }
        private async Task<List<PendingGitHubOperation>> ReadAsync() { await gate.WaitAsync(); try { return Read(); } finally { gate.Release(); } }
        private async Task RemoveAsync(Guid id) { await gate.WaitAsync(); try { List<PendingGitHubOperation> all = Read(); all.RemoveAll(x => x.Id == id); Write(all); } finally { gate.Release(); } }
        private async Task ReplaceAsync(PendingGitHubOperation value) { await gate.WaitAsync(); try { List<PendingGitHubOperation> all = Read(); int index = all.FindIndex(x => x.Id == value.Id); if (index >= 0) all[index] = value; Write(all); } finally { gate.Release(); } }
        private List<PendingGitHubOperation> Read() { try { return File.Exists(path) ? JsonConvert.DeserializeObject<List<PendingGitHubOperation>>(File.ReadAllText(path)) ?? new List<PendingGitHubOperation>() : new List<PendingGitHubOperation>(); } catch { return new List<PendingGitHubOperation>(); } }
        private void Write(List<PendingGitHubOperation> values) { string temp = path + ".tmp"; File.WriteAllText(temp, JsonConvert.SerializeObject(values, Formatting.Indented)); if (File.Exists(path)) File.Replace(temp, path, path + ".bak", true); else File.Move(temp, path); }
        private static bool Mapped(WorkTask task, out int number) { number = 0; return task != null && task.Source == TaskSource.GitHub && int.TryParse(task.ExternalId, out number) && number > 0; }
        private static string Safe(string value) { return string.IsNullOrWhiteSpace(value) ? "GitHub synchronization failed." : value.Length > 300 ? value.Substring(0, 300) : value; }
        private static string OperationText(PendingGitHubOperation value) { if (value.OperationType == GitHubOperationType.CloseIssue) return "GitHub Issue #" + value.IssueNumber + " closed"; if (value.OperationType == GitHubOperationType.ReopenIssue) return "GitHub Issue #" + value.IssueNumber + " reopened"; if (value.OperationType == GitHubOperationType.AddComment) return "GitHub Issue #" + value.IssueNumber + " comment synchronized"; if (value.OperationType == GitHubOperationType.UpdateIssueBody) return "GitHub Issue #" + value.IssueNumber + " body synchronized"; return value.OperationType == GitHubOperationType.AddProjectItem ? "GitHub Project item added" : "GitHub Project status synchronized"; }
    }
}
