using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;
namespace SlaveSplit.Services.GitHub
{
    public interface IGitHubProjectService { Task<GitHubProjectsResult> GetProjectsAsync(string owner, CancellationToken token); Task<GitHubProjectItemResult> AddItemAsync(string projectId, string contentNodeId, CancellationToken token); Task<GitHubProjectItemResult> UpdateStatusAsync(string projectId, string itemId, string fieldId, string optionId, CancellationToken token); }
    public sealed class GitHubProjectService : IGitHubProjectService
    {
        private readonly GitHubClient client; private readonly IGitHubCredentialProvider credentials;
        public GitHubProjectService(GitHubClient client, IGitHubCredentialProvider credentials) { this.client = client; this.credentials = credentials; }
        public async Task<GitHubProjectsResult> GetProjectsAsync(string owner, CancellationToken token)
        {
            const string query = "query($login:String!){user(login:$login){projectsV2(first:50){nodes{id title fields(first:50){nodes{... on ProjectV2SingleSelectField{id name options{id name}}}}}}}organization(login:$login){projectsV2(first:50){nodes{id title fields(first:50){nodes{... on ProjectV2SingleSelectField{id name options{id name}}}}}}}}";
            try { using (HttpResponseMessage response = await client.GraphQLAsync(query, new { login = owner }, credentials.GetToken(), token)) { string json = await response.Content.ReadAsStringAsync(); if (!response.IsSuccessStatusCode) return Fail("GitHub Project query failed. Check Projects read permission."); JObject root = JObject.Parse(json); JToken projects = root.SelectToken("data.user.projectsV2.nodes") ?? root.SelectToken("data.organization.projectsV2.nodes"); if (projects == null) return Fail("No accessible GitHub Projects found. Check owner and token permission."); GitHubProjectsResult result = new GitHubProjectsResult { Success = true, Message = "Projects loaded." }; foreach (JToken node in projects) { if (node == null || node.Type != JTokenType.Object) continue; GitHubProjectInfo project = new GitHubProjectInfo { Id = (string)node["id"], Title = (string)node["title"] }; JToken fields = node.SelectToken("fields.nodes"); if (fields != null && fields.Type == JTokenType.Array) foreach (JToken field in fields) { if (field == null || field.Type != JTokenType.Object || field["options"] == null) continue; GitHubProjectStatusField value = new GitHubProjectStatusField { Id = (string)field["id"], Name = (string)field["name"] }; foreach (JToken option in field["options"]) { if (option != null && option.Type == JTokenType.Object) value.Options.Add(new GitHubProjectStatusOption { Id = (string)option["id"], Name = (string)option["name"] }); } project.StatusFields.Add(value); } result.Projects.Add(project); } return result; } } catch (Exception ex) { return Fail("GitHub Project query failed: " + ex.Message); }
        }
        public async Task<GitHubProjectItemResult> AddItemAsync(string projectId, string contentNodeId, CancellationToken token) { const string mutation = "mutation($project:ID!,$content:ID!){addProjectV2ItemById(input:{projectId:$project,contentId:$content}){item{id}}}"; return await MutateAsync(mutation, new { project = projectId, content = contentNodeId }, "data.addProjectV2ItemById.item.id", token); }
        public async Task<GitHubProjectItemResult> UpdateStatusAsync(string projectId, string itemId, string fieldId, string optionId, CancellationToken token) { const string mutation = "mutation($project:ID!,$item:ID!,$field:ID!,$option:String!){updateProjectV2ItemFieldValue(input:{projectId:$project,itemId:$item,fieldId:$field,value:{singleSelectOptionId:$option}}){projectV2Item{id}}}"; return await MutateAsync(mutation, new { project = projectId, item = itemId, field = fieldId, option = optionId }, "data.updateProjectV2ItemFieldValue.projectV2Item.id", token); }
        private async Task<GitHubProjectItemResult> MutateAsync(string query, object variables, string path, CancellationToken token) { try { using (HttpResponseMessage response = await client.GraphQLAsync(query, variables, credentials.GetToken(), token)) { string json = await response.Content.ReadAsStringAsync(); if (!response.IsSuccessStatusCode) return new GitHubProjectItemResult { Success = false, Message = "GitHub Project update failed. Check Projects write permission." }; JObject root = JObject.Parse(json); string id = (string)root.SelectToken(path); if (string.IsNullOrWhiteSpace(id)) return new GitHubProjectItemResult { Success = false, Message = "GitHub Project update failed." }; return new GitHubProjectItemResult { Success = true, Message = "GitHub Project synchronized.", ItemId = id }; } } catch { return new GitHubProjectItemResult { Success = false, Message = "GitHub Project is unavailable." }; } }
        private static GitHubProjectsResult Fail(string message) { return new GitHubProjectsResult { Success = false, Message = message }; }
    }
}
