using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Input;
using SlaveSplit.AgentTests;
using SlaveSplit.Commands;

namespace SlaveSplit.ViewModels
{
    public sealed class AgentTestRunnerViewModel : ViewModelBase
    {
        private readonly AgentScenarioTestRunner runner = new AgentScenarioTestRunner(); private readonly TaskBoardTestRunner boardRunner=new TaskBoardTestRunner(); private bool isBusy; private string summary="실행 전",copyStatus,localAiPreflight="실행 전"; private AgentTestResult selectedResult;
        public AgentTestRunnerViewModel(){Results=new ObservableCollection<AgentTestResult>();RunAllCommand=new RelayCommand(async p=>await RunAsync(AgentTestScenarioRegistry.All().Where(x=>x.Mode==AgentTestMode.Fast||x.Mode==AgentTestMode.LocalLlm)),p=>!IsBusy);RunCurrentCommand=new RelayCommand(async p=>await RunAsync(AgentTestScenarioRegistry.All().Where(x=>x.Group==AgentTestScenarioRegistry.CurrentGroup&&x.Mode!=AgentTestMode.GitHub)),p=>!IsBusy);CopyResultsCommand=new RelayCommand(p=>CopyResults(),p=>Results.Count>0);}
        public ObservableCollection<AgentTestResult> Results{get;private set;} public ICommand RunAllCommand{get;private set;} public ICommand RunCurrentCommand{get;private set;} public ICommand CopyResultsCommand{get;private set;}
        public bool IsBusy{get{return isBusy;}private set{if(SetProperty(ref isBusy,value))CommandManager.InvalidateRequerySuggested();}} public string Summary{get{return summary;}private set{SetProperty(ref summary,value);}} public string CopyStatus{get{return copyStatus;}private set{SetProperty(ref copyStatus,value);}} public AgentTestResult SelectedResult{get{return selectedResult;}set{SetProperty(ref selectedResult,value);}}
        public string LocalAiPreflight{get{return localAiPreflight;}private set{SetProperty(ref localAiPreflight,value);}}
        public string SafetyBanner{get{return "TEST MODE · Repository: InMemory · GitHub Mutation: OFF";}}
        private async System.Threading.Tasks.Task RunAsync(IEnumerable<AgentTestScenario> scenarios){IsBusy=true;CopyStatus=null;try{Results.Clear();foreach(AgentTestResult item in await runner.RunAsync(scenarios))Results.Add(item);foreach(AgentTestResult item in await boardRunner.RunAsync())Results.Add(item);UpdatePreflight();UpdateSummary();}catch(Exception ex){Summary="테스트 실행 실패: "+ex.Message;}finally{IsBusy=false;CommandManager.InvalidateRequerySuggested();}}
        public string BuildReport(){StringBuilder text=new StringBuilder("[SlaveSplit Agent Test Result]\n\nDate: ").Append(DateTime.Now.ToString("yyyy-MM-dd HH:mm")).Append("\n\nLocal AI Preflight:\n").Append(LocalAiPreflight).Append("\n\n").Append(Summary);IList<AgentTestResult> failed=Results.Where(x=>!x.Passed&&!x.Skipped).ToList();text.Append("\n\n## Failed");if(failed.Count==0)text.Append("\nNone");foreach(AgentTestResult x in failed)text.Append("\n\n[").Append(x.Group).Append(" / ").Append(x.Scenario).Append("]\nInput: ").Append(x.Input).Append("\nExpected: ").Append(x.Expected).Append("\nActual: ").Append(x.Actual).Append("\nFallbackRequired: ").Append(x.FallbackRequested).Append("\nLLM Called: ").Append(x.LlmCalled).Append("\nLLM Success: ").Append(x.LlmSuccess).Append("\nLLM Failure: ").Append(x.LlmFailureKind??"NONE").Append("\nRaw Output: ").Append(x.LlmRawOutput??"-").Append("\nSource: ").Append(x.Source).Append("\nFailure: ").Append(x.FailureReason);IList<AgentTestResult> wrong=Results.Where(x=>x.WrongMutation).ToList();text.Append("\n\n## Wrong Mutations");if(wrong.Count==0)text.Append("\nNone");foreach(AgentTestResult x in wrong)text.Append("\n\nScenario: ").Append(x.Scenario).Append("\nStep: ").Append(x.Step).Append("\nInput: ").Append(x.Input).Append("\nExpected Mutation: ").Append(x.ExpectedMutationCount).Append("\nActual Mutation: ").Append(x.ActualMutationCount).Append("\nAffected Tasks: ").Append(x.AffectedTasks).Append("\nBefore: ").Append(x.BeforeState).Append("\nAfter: ").Append(x.AfterState).Append("\nSource: ").Append(x.Source);return text.ToString();}
        private void CopyResults(){try{Clipboard.SetText(BuildReport());CopyStatus="결과를 클립보드에 복사했습니다.";}catch{CopyStatus="결과를 복사하지 못했습니다.";}}
        private void UpdateSummary(){int pass=Results.Count(x=>x.Passed),skipped=Results.Count(x=>x.Skipped),fail=Results.Count-pass-skipped;Summary="Total: "+Results.Count+" · Passed: "+pass+" · Failed: "+fail+" · Skipped: "+skipped+"\nFAST: "+Results.Count(x=>x.Mode==AgentTestMode.Fast)+" · LOCAL LLM: "+Results.Count(x=>x.Mode==AgentTestMode.LocalLlm)+" · INTEGRATION: 0 · GITHUB: 0\nParser Used: "+Results.Count(x=>x.Source=="PARSER")+" · Fallback Requested: "+Results.Count(x=>x.FallbackRequested)+" · LLM Called: "+Results.Count(x=>x.LlmCalled)+" · LLM Success: "+Results.Count(x=>x.LlmSuccess)+" · LLM Failed: "+Results.Count(x=>x.LlmCalled&&!x.LlmSuccess)+" · LLM Skipped: "+skipped+"\nUnresolved: "+Results.Count(x=>x.Source=="UNRESOLVED")+" · Avg Latency: "+(Results.Count==0?0:Results.Average(x=>x.LatencyMs))+" ms · Wrong Mutation: "+Results.Count(x=>x.WrongMutation)+" · Production Mutation: 0 · GitHub Mutation: 0";}
        private void UpdatePreflight(){LocalAiPreflightResult p=runner.LastPreflight;LocalAiPreflight=p==null?"NOT REQUIRED":"Enabled: "+(p.Enabled?"YES":"NO")+" · Endpoint: "+p.Endpoint+" · Connected: "+(p.Connected?"YES":"NO")+" · Model: "+p.Model+" · Model Found: "+(p.ModelFound?"YES":"NO")+" · Generate: "+(p.GenerateSuccess?"PASS":"FAIL")+" · Failure: "+p.FailureReason+" · Service: "+p.ServiceType+" · "+p.GenerateLatencyMs+" ms";}
    }
}
