using System;
using System.Threading;
using System.Windows.Input;
using SlaveSplit.Commands;
using SlaveSplit.Models;
using SlaveSplit.Services;
using SlaveSplit.Services.GitHub;
namespace SlaveSplit.ViewModels
{
    public sealed class GitHubIssueDetailViewModel : ViewModelBase
    {
        private readonly int number; private readonly IGitHubService service; private readonly GitHubSettings settings; private readonly GitHubNavigationService navigation; private readonly IGitHubTaskMappingService mappings; private readonly TaskNavigationService taskNavigation; private CancellationTokenSource request; private GitHubIssueInfo issue; private WorkTask trackedTask, selectedTask; private bool isLoading, isMapping; private string errorMessage, mappingMessage;
        public GitHubIssueDetailViewModel(int number, IGitHubService service, GitHubSettings settings, GitHubNavigationService navigation, IGitHubTaskMappingService mappings, TaskNavigationService taskNavigation) { this.number = number; this.service = service; this.settings = settings; this.navigation = navigation; this.mappings = mappings; this.taskNavigation = taskNavigation; LinkCandidates = new System.Collections.ObjectModel.ObservableCollection<WorkTask>(); BackCommand = new RelayCommand(p => navigation.Back()); RefreshCommand = new RelayCommand(async p => await LoadAsync(), p => !IsLoading); OpenGitHubCommand = new RelayCommand(p => OpenGitHub(), p => CanOpenGitHub); TrackCommand = new RelayCommand(async p => await TrackAsync(), p => Issue != null && !IsTracked && !IsMapping); LinkCommand = new RelayCommand(async p => await LinkAsync(), p => Issue != null && SelectedTask != null && !IsTracked && !IsMapping); OpenTaskCommand = new RelayCommand(p => { if (TrackedTask != null) taskNavigation.Open(TrackedTask.Id); }, p => IsTracked); Initialize(); }
        public GitHubIssueInfo Issue { get { return issue; } private set { SetProperty(ref issue, value); OnPropertyChanged("CanOpenGitHub"); CommandManager.InvalidateRequerySuggested(); } } public WorkTask TrackedTask { get { return trackedTask; } private set { SetProperty(ref trackedTask, value); OnPropertyChanged("IsTracked"); CommandManager.InvalidateRequerySuggested(); } } public bool IsTracked { get { return TrackedTask != null; } } public System.Collections.ObjectModel.ObservableCollection<WorkTask> LinkCandidates { get; private set; } public WorkTask SelectedTask { get { return selectedTask; } set { if (SetProperty(ref selectedTask, value)) CommandManager.InvalidateRequerySuggested(); } }
        public bool IsLoading { get { return isLoading; } private set { if (SetProperty(ref isLoading, value)) CommandManager.InvalidateRequerySuggested(); } } public bool IsMapping { get { return isMapping; } private set { if (SetProperty(ref isMapping, value)) CommandManager.InvalidateRequerySuggested(); } } public string ErrorMessage { get { return errorMessage; } private set { SetProperty(ref errorMessage, value); } } public string MappingMessage { get { return mappingMessage; } private set { SetProperty(ref mappingMessage, value); } } public bool CanOpenGitHub { get { Uri uri; return Issue != null && Uri.TryCreate(Issue.HtmlUrl, UriKind.Absolute, out uri) && uri.Scheme == Uri.UriSchemeHttps && string.Equals(uri.Host, "github.com", StringComparison.OrdinalIgnoreCase); } }
        public ICommand BackCommand { get; private set; } public ICommand RefreshCommand { get; private set; } public ICommand OpenGitHubCommand { get; private set; } public ICommand TrackCommand { get; private set; } public ICommand LinkCommand { get; private set; } public ICommand OpenTaskCommand { get; private set; }
        public async System.Threading.Tasks.Task LoadAsync() { if (request != null) { request.Cancel(); request.Dispose(); } request = new CancellationTokenSource(); IsLoading = true; ErrorMessage = null; try { GitHubIssueResult result = await service.GetIssueAsync(settings, number, request.Token); if (result.Success) { Issue = result.Issue; await LoadMappingAsync(); } else ErrorMessage = result.Message; } catch (OperationCanceledException) { } finally { IsLoading = false; } }
        private async System.Threading.Tasks.Task LoadMappingAsync() { TrackedTask = await mappings.GetTrackedTaskAsync(number); LinkCandidates.Clear(); if (!IsTracked) foreach (WorkTask task in await mappings.GetLinkCandidatesAsync()) LinkCandidates.Add(task); }
        private async System.Threading.Tasks.Task TrackAsync() { IsMapping = true; MappingMessage = null; try { bool existed = await mappings.IsTrackedAsync(number); TrackedTask = await mappings.TrackIssueAsync(Issue); MappingMessage = existed ? "Already tracked in SlaveSplit." : "Tracked in SlaveSplit."; } catch (Exception ex) { MappingMessage = ex.Message; } finally { IsMapping = false; } }
        private async System.Threading.Tasks.Task LinkAsync() { IsMapping = true; MappingMessage = null; try { bool existed = await mappings.IsTrackedAsync(number); TrackedTask = await mappings.LinkExistingTaskAsync(Issue, SelectedTask); MappingMessage = existed ? "Already tracked in SlaveSplit." : "Existing task linked to GitHub Issue #" + number + "."; } catch (Exception ex) { MappingMessage = ex.Message; } finally { IsMapping = false; } }
        private async void Initialize() { await LoadAsync(); } private void OpenGitHub() { if (!CanOpenGitHub) return; try { System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(Issue.HtmlUrl) { UseShellExecute = true }); } catch { ErrorMessage = "Could not open GitHub."; } }
    }
}
