using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using System.Windows.Input;
using SlaveSplit.Commands;
using SlaveSplit.Services.GitHub;
namespace SlaveSplit.ViewModels
{
    public sealed class GitHubViewModel : ViewModelBase
    {
        private readonly IGitHubService service; private readonly GitHubSettings settings; private readonly GitHubNavigationService navigation; private readonly IGitHubTaskMappingService mappings; private readonly IGitHubSyncService sync; private readonly Dictionary<GitHubIssueState, List<GitHubIssueInfo>> cache = new Dictionary<GitHubIssueState, List<GitHubIssueInfo>>(); private CancellationTokenSource request; private string searchText, selectedLabel = "All labels", errorMessage, syncMessage; private GitHubIssueState selectedState = GitHubIssueState.Open; private GitHubIssueSort selectedSort = GitHubIssueSort.RecentlyUpdated; private bool isLoading, hasNextPage; private int currentPage, pendingCount;
        public GitHubViewModel(IGitHubService service, GitHubSettings settings, GitHubNavigationService navigation, IGitHubTaskMappingService mappings, IGitHubSyncService sync = null) { this.service = service; this.settings = settings; this.navigation = navigation; this.mappings = mappings; this.sync = sync; Issues = new ObservableCollection<GitHubIssueInfo>(); States = new[] { GitHubIssueState.All, GitHubIssueState.Open, GitHubIssueState.Closed }; SortOptions = new[] { GitHubIssueSort.RecentlyUpdated, GitHubIssueSort.Newest, GitHubIssueSort.Oldest }; Labels = new ObservableCollection<string>(); RefreshCommand = new RelayCommand(async p => await LoadAsync(true), p => !IsLoading); SyncAllCommand = new RelayCommand(async p => await SyncAllAsync(), p => sync != null && PendingCount > 0 && !IsLoading); LoadMoreCommand = new RelayCommand(async p => await LoadMoreAsync(), p => !IsLoading && HasNextPage); FilterCommand = new RelayCommand(async p => { if (p is GitHubIssueState) SelectedState = (GitHubIssueState)p; await LoadAsync(false); }, p => !IsLoading); SearchCommand = new RelayCommand(p => ApplyFilter()); OpenIssueCommand = new RelayCommand(p => { GitHubIssueInfo issue = p as GitHubIssueInfo; if (issue != null) navigation.OpenIssue(issue.Number); }); OpenSettingsCommand = new RelayCommand(p => navigation.OpenSettings()); mappings.MappingChanged += async delegate { await AnnotateTrackingAsync(); ApplyFilter(); }; Initialize(); }
        public ObservableCollection<GitHubIssueInfo> Issues { get; private set; } public GitHubIssueState[] States { get; private set; } public GitHubIssueSort[] SortOptions { get; private set; } public ObservableCollection<string> Labels { get; private set; }
        public string RepositoryText { get { return settings.Owner + " / " + settings.Repository; } } public bool IsConfigured { get { return settings.Enabled && !string.IsNullOrWhiteSpace(settings.Owner) && !string.IsNullOrWhiteSpace(settings.Repository); } } public bool IsLoading { get { return isLoading; } private set { if (SetProperty(ref isLoading, value)) { CommandManager.InvalidateRequerySuggested(); OnPropertyChanged("LoadingText"); } } } public string LoadingText { get { return IsLoading ? (currentPage > 1 ? "Loading more issues..." : "Loading GitHub issues...") : ""; } } public string ErrorMessage { get { return errorMessage; } private set { SetProperty(ref errorMessage, value); OnPropertyChanged("HasError"); } } public bool HasError { get { return !string.IsNullOrWhiteSpace(ErrorMessage); } } public bool IsEmpty { get { return !IsLoading && !HasError && IsConfigured && Issues.Count == 0; } } public bool HasNextPage { get { return hasNextPage; } private set { SetProperty(ref hasNextPage, value); CommandManager.InvalidateRequerySuggested(); } }
        public string SearchText { get { return searchText; } set { if (SetProperty(ref searchText, value)) ApplyFilter(); } } public string SelectedLabel { get { return selectedLabel; } set { if (SetProperty(ref selectedLabel, value)) ApplyFilter(); } } public GitHubIssueState SelectedState { get { return selectedState; } set { SetProperty(ref selectedState, value); } } public GitHubIssueSort SelectedSort { get { return selectedSort; } set { if (SetProperty(ref selectedSort, value)) ApplyFilter(); } }
        public int PendingCount { get { return pendingCount; } private set { if (SetProperty(ref pendingCount, value)) CommandManager.InvalidateRequerySuggested(); } } public string SyncButtonText { get { return "Sync Pending (" + PendingCount + ")"; } } public string SyncMessage { get { return syncMessage; } private set { SetProperty(ref syncMessage, value); } }
        public ICommand RefreshCommand { get; private set; } public ICommand SyncAllCommand { get; private set; } public ICommand LoadMoreCommand { get; private set; } public ICommand FilterCommand { get; private set; } public ICommand SearchCommand { get; private set; } public ICommand OpenIssueCommand { get; private set; } public ICommand OpenSettingsCommand { get; private set; }
        public void ResetCache(){cache.Clear();Issues.Clear();}
        public async System.Threading.Tasks.Task LoadAsync(bool force) { if (!IsConfigured) { Issues.Clear(); ErrorMessage = "GitHub isn't connected. Configure GitHub in Settings."; OnPropertyChanged("IsEmpty"); return; } if (!force && cache.ContainsKey(SelectedState)) { currentPage = 1; await AnnotateTrackingAsync(); ApplyFilter(); return; } Cancel(); request = new CancellationTokenSource(); IsLoading = true; ErrorMessage = null; currentPage = 1; try { GitHubIssuesResult result = await service.GetIssuesAsync(settings, Query(currentPage), request.Token); if (!result.Success) { Issues.Clear(); ErrorMessage = result.Message; return; } cache[SelectedState] = result.Issues.GroupBy(x => x.Number).Select(x => x.First()).ToList(); await AnnotateTrackingAsync(); HasNextPage = result.HasNextPage; RebuildLabels(); ApplyFilter(); } catch (OperationCanceledException) { } finally { IsLoading = false; OnPropertyChanged("IsEmpty"); } }
        private async System.Threading.Tasks.Task LoadMoreAsync() { if (!HasNextPage || IsLoading) return; IsLoading = true; currentPage++; try { GitHubIssuesResult result = await service.GetIssuesAsync(settings, Query(currentPage), CancellationToken.None); if (!result.Success) { ErrorMessage = result.Message; currentPage--; return; } List<GitHubIssueInfo> values = cache.ContainsKey(SelectedState) ? cache[SelectedState] : new List<GitHubIssueInfo>(); foreach (GitHubIssueInfo issue in result.Issues) if (!values.Any(x => x.Number == issue.Number)) values.Add(issue); cache[SelectedState] = values; await AnnotateTrackingAsync(); HasNextPage = result.HasNextPage; RebuildLabels(); ApplyFilter(); } finally { IsLoading = false; } }
        private async System.Threading.Tasks.Task AnnotateTrackingAsync() { IReadOnlyList<SlaveSplit.Models.WorkTask> all = await mappings.GetTrackedTasksAsync(); foreach (List<GitHubIssueInfo> list in cache.Values) foreach (GitHubIssueInfo issue in list) { SlaveSplit.Models.WorkTask task = all.FirstOrDefault(x => x.ExternalId == issue.Number.ToString()); issue.IsTracked = task != null; issue.TrackedTaskId = task == null ? (Guid?)null : task.Id; } }
        private async System.Threading.Tasks.Task SyncAllAsync() { if (sync == null) return; IsLoading = true; try { int count = await sync.RetryAllAsync(); SyncMessage = count + " operation(s) synchronized."; await RefreshPendingAsync(); } finally { IsLoading = false; } }
        private async System.Threading.Tasks.Task RefreshPendingAsync() { PendingCount = sync == null ? 0 : await sync.GetPendingCountAsync(); OnPropertyChanged("SyncButtonText"); }
        private GitHubIssueQuery Query(int page) { return new GitHubIssueQuery { State = SelectedState, Page = page, PerPage = 50, Sort = SelectedSort }; }
        private void ApplyFilter() { IEnumerable<GitHubIssueInfo> values; if (!cache.TryGetValue(SelectedState, out List<GitHubIssueInfo> list)) values = new List<GitHubIssueInfo>(); else values = list; if (!string.IsNullOrWhiteSpace(SearchText)) { string value = SearchText.Trim(); values = values.Where(x => x.Number.ToString() == value.TrimStart('#') || (x.Title ?? "").IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0 || (x.Body ?? "").IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0 || x.Labels.Any(l => (l.Name ?? "").IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0)); } if (!string.IsNullOrWhiteSpace(SelectedLabel) && SelectedLabel != "All labels") values = values.Where(x => x.Labels.Any(l => string.Equals(l.Name, SelectedLabel, StringComparison.OrdinalIgnoreCase))); if (SelectedSort == GitHubIssueSort.Newest) values = values.OrderByDescending(x => x.CreatedAt); else if (SelectedSort == GitHubIssueSort.Oldest) values = values.OrderBy(x => x.CreatedAt); else values = values.OrderByDescending(x => x.UpdatedAt); Issues.Clear(); foreach (GitHubIssueInfo issue in values) Issues.Add(issue); OnPropertyChanged("IsEmpty"); }
        private void RebuildLabels() { string selected = SelectedLabel; Labels.Clear(); Labels.Add("All labels"); if (cache.TryGetValue(SelectedState, out List<GitHubIssueInfo> values)) foreach (string label in values.SelectMany(x => x.Labels).Select(x => x.Name).Where(x => !string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(x => x)) Labels.Add(label); SelectedLabel = Labels.Contains(selected) ? selected : "All labels"; }
        private async void Initialize() { await RefreshPendingAsync(); await LoadAsync(false); } private void Cancel() { if (request != null) { request.Cancel(); request.Dispose(); request = null; } }
    }
}
