using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Input;
using Newtonsoft.Json;
using SlaveSplit.Agents;
using SlaveSplit.Commands;
using SlaveSplit.Models;
using SlaveSplit.Services;
using SlaveSplit.Services.LocalLlm;

namespace SlaveSplit.ViewModels
{
    public sealed class LocalLlmPocViewModel : ViewModelBase
    {
        private const string RegressionInput = "2번만 Done으로 해줘"; private readonly ILocalLlmService llm; private readonly LocalLlmSettings localSettings; private readonly TaskService tasks; private readonly AgentConversationService chatAnalyzer; private readonly IHybridCommandInterpreter hybrid;
        private string activeRunId = "adhoc";
        private string input = RegressionInput, context, selectedModel, currentResult, graniteResult, hybridResult, decisionReason, metrics, statusText = "Ollama 연결 확인 전", summary, hybridSummary, localAiStatus = "UNKNOWN", localAiLastError = "없음"; private bool isBusy;
        public LocalLlmPocViewModel(TaskService tasks, AgentConversationService chatAnalyzer) { this.tasks = tasks; this.chatAnalyzer = chatAnalyzer; localSettings = LocalLlmSettings.Load(); llm = new GraniteOllamaService(localSettings.Endpoint, TimeSpan.FromSeconds(localSettings.TimeoutSeconds)); hybrid = new HybridCommandInterpreter(chatAnalyzer, llm); ConnectCommand = new RelayCommand(async p => await ConnectAsync(), p => !IsBusy); RunCommand = new RelayCommand(async p => await RunOneAsync(), p => !IsBusy); RunSuiteCommand = new RelayCommand(async p => await RunSuiteAsync(), p => !IsBusy); Context = "1. MCC 로그 분석 - Todo\n2. 외근 결과 보고 - InProgress\n3. FMP CIM 분석 - Done"; Results = new ObservableCollection<BenchmarkRow>(); }
        public ObservableCollection<BenchmarkRow> Results { get; private set; }
        public string Input { get { return input; } set { SetProperty(ref input, value); } } public string Context { get { return context; } set { SetProperty(ref context, value); } } public string SelectedModel { get { return selectedModel; } set { if (SetProperty(ref selectedModel, value)) LocalLlmSettings.SetRuntimeModel(value); } }
        public string CurrentResult { get { return currentResult; } set { SetProperty(ref currentResult, value); } } public string GraniteResult { get { return graniteResult; } set { SetProperty(ref graniteResult, value); } } public string Metrics { get { return metrics; } set { SetProperty(ref metrics, value); } }
        public string StatusText { get { return statusText; } set { SetProperty(ref statusText, value); } } public string Summary { get { return summary; } set { SetProperty(ref summary, value); } } public bool IsBusy { get { return isBusy; } set { SetProperty(ref isBusy, value); CommandManager.InvalidateRequerySuggested(); } }
        public string HybridSummary { get { return hybridSummary; } set { SetProperty(ref hybridSummary, value); } }
        public string HybridResult { get { return hybridResult; } set { SetProperty(ref hybridResult, value); } } public string DecisionReason { get { return decisionReason; } set { SetProperty(ref decisionReason, value); } }
        public string LocalAiStatus { get { return localAiStatus; } set { SetProperty(ref localAiStatus, value); } } public string LocalAiEndpoint { get { return localSettings.Endpoint; } } public string LocalAiLastError { get { return localAiLastError; } set { SetProperty(ref localAiLastError, value); } }
        public ICommand ConnectCommand { get; private set; } public ICommand RunCommand { get; private set; } public ICommand RunSuiteCommand { get; private set; }
        private async Task ConnectAsync() { IsBusy = true; try { if (!localSettings.Enabled) { LocalAiStatus = "DISABLED"; LocalAiLastError = LocalAiFailureKind.Disabled; StatusText = "Local AI 비활성화"; return; } LocalAiAvailability state = await llm.CheckAvailabilityAsync(localSettings.EffectiveModel, CancellationToken.None); LocalAiStatus = state.Online ? "ONLINE" : "OFFLINE"; LocalAiLastError = state.FailureKind ?? "없음"; SelectedModel = state.Online ? state.Model : localSettings.EffectiveModel; StatusText = state.Online ? "연결됨 · " + state.Model : "연결 실패 · " + state.FailureKind; if (state.Online) await LoadContextAsync(); } catch (Exception ex) { LocalAiStatus = "OFFLINE"; LocalAiLastError = LocalAiFailureKind.RequestError; StatusText = "연결 실패 · " + ex.Message; } finally { IsBusy = false; } }
        private async Task LoadContextAsync() { IReadOnlyList<WorkTask> all = await tasks.GetAllAsync(); if (all.Count > 0) Context = string.Join("\n", all.Take(20).Select((x, i) => (i + 1) + ". " + x.Title + " - " + x.Status)); }
        private async Task EnsureModelAsync() { if (string.IsNullOrWhiteSpace(SelectedModel)) await ConnectAsync(); }
        private async Task RunOneAsync() { IsBusy = true; try { await EnsureModelAsync(); if (string.IsNullOrWhiteSpace(SelectedModel)) return; TestCase item = new TestCase { Input = Input }; ParserComparisonRecord record = await ExecuteAsync(item, Results.Count + 1); Show(record); } finally { IsBusy = false; } }
        private async Task<ParserComparisonRecord> ExecuteAsync(TestCase test, int no)
        {
            IList<WorkTask> candidates = CandidateTasks(); HybridCommandResult hybridDecision = await hybrid.InterpretAsync(test.Input, candidates, Context, SelectedModel, CancellationToken.None); AgentDryRunResult current = hybridDecision.ParserResult; LocalLlmResponse response = hybridDecision.LlmResponse ?? await llm.ParseAsync(new LocalLlmRequest { Input = test.Input, CandidateContext = Context, Model = SelectedModel }, CancellationToken.None);
            bool hasExpected = !string.IsNullOrWhiteSpace(test.Intent); bool currentPass = hasExpected && ParserComparisonService.Matches(test.Intent, test.Targets, test.Status, test.Keyword, test.Reference, test.Title, current); bool semantic = hasExpected && response.SchemaSuccess && ParserComparisonService.Matches(test.Intent, test.Targets, test.Status, test.Keyword, test.Reference, test.Title, response.Result);
            bool evaluationPass = response.SchemaSuccess && semantic; bool final = response.JsonParseSuccess && response.SchemaSuccess && semantic && evaluationPass; string failure = !response.JsonParseSuccess ? "JSON_FAIL" : !response.SchemaSuccess ? "SCHEMA_FAIL: " + response.SchemaError : !semantic ? "SEMANTIC_FAIL" : !evaluationPass ? "EVALUATION_FAIL" : "PASS";
            bool pathMatch = !(string.Equals(test.Input, RegressionInput, StringComparison.Ordinal) && currentPass); if (!pathMatch) failure = "BENCHMARK_PATH_MISMATCH · historical Chat FAIL vs DryRun PASS";
            bool hybridPass = hasExpected && hybridDecision.Result != null && ParserComparisonService.Matches(test.Intent, test.Targets, test.Status, test.Keyword, test.Reference, test.Title, hybridDecision.Result);
            ParserComparisonRecord record = new ParserComparisonRecord { RecordedAt = DateTime.Now, RunId = activeRunId, PromptVersion = "Patch-02-Structured-v1", No = no, Input = test.Input, ExpectedIntent = test.Intent, ExpectedTargets = test.Targets, ExpectedKeyword = test.Keyword, ExpectedReference = test.Reference, ExpectedTitle = test.Title, ExpectedStatus = test.Status, CurrentParserResult = current, CurrentParserPass = currentPass, BenchmarkPathMatch = pathMatch, GraniteRawResponse = response.RawOutput, GraniteResult = response.Result, JsonPass = response.JsonParseSuccess, SchemaPass = response.SchemaSuccess, SemanticPass = semantic, EvaluationPass = evaluationPass, FinalPass = final && pathMatch, FailureKind = failure, Metrics = response, HybridResult = hybridDecision, HybridPass = hybridPass };
            try { HybridCommandInterpreter.Save(activeRunId, no, test.Input, hybridDecision); } catch { }
            try { StatusText = "결과 저장됨 · " + ParserComparisonService.Save(record); } catch (Exception ex) { StatusText = "결과 저장 실패 · " + ex.Message; } Results.Add(new BenchmarkRow(record)); return record;
        }
        private void Show(ParserComparisonRecord record) { CurrentResult = record.CurrentParserResult.Display; GraniteResult = record.GraniteRawResponse ?? record.Metrics.Error; HybridResult = record.HybridResult.Source + " · " + (record.HybridResult.Result == null ? "NEEDS_CLARIFICATION" : record.HybridResult.Result.Intent + " [" + string.Join(",", record.HybridResult.Result.TargetIndexes) + "] " + (record.HybridResult.Result.Status ?? "null")) + " · Fallback " + (record.HybridResult.FallbackCalled ? "YES" : "NO") + " · " + Pass(record.HybridPass); DecisionReason = record.HybridResult.Reason; Metrics = "ColdStart " + record.Metrics.ColdStart + " · " + record.Metrics.LatencyMs + " ms · JSON " + Pass(record.JsonPass) + " · Schema " + Pass(record.SchemaPass) + " · Slave RAM " + record.Metrics.ProcessWorkingSetMB + " MB · Ollama RAM " + record.Metrics.OllamaWorkingSetMB + " MB · Model " + record.Metrics.ModelMemoryMB + " MB (VRAM " + record.Metrics.ModelVramMB + " MB)"; }
        private async Task RunSuiteAsync()
        {
            IsBusy = true; try { await EnsureModelAsync(); if (string.IsNullOrWhiteSpace(SelectedModel)) return; activeRunId = DateTime.Now.ToString("yyyyMMdd-HHmmss") + "-" + Guid.NewGuid().ToString("N").Substring(0, 6); Results.Clear(); List<TestCase> suite = Cases(); List<ParserComparisonRecord> records = new List<ParserComparisonRecord>(); for (int i = 0; i < suite.Count; i++) { StatusText = "테스트 " + (i + 1) + "/" + suite.Count + " · " + suite[i].Input; ParserComparisonRecord record = await ExecuteAsync(suite[i], i + 1); records.Add(record); Show(record); }
                List<ParserComparisonRecord> warm = records.Where(x => !x.Metrics.ColdStart).ToList(); ParserComparisonRecord cold = records.FirstOrDefault(x => x.Metrics.ColdStart); bool path = records.All(x => x.BenchmarkPathMatch); Summary = "AI Test Summary\nCurrent Parser Accuracy: " + Rate(records.Count(x => x.CurrentParserPass), records.Count) + "\nQwen Semantic Accuracy: " + Rate(records.Count(x => x.SemanticPass), records.Count) + "\nQwen Schema Success: " + Rate(records.Count(x => x.SchemaPass), records.Count) + "\nQwen Final Accuracy: " + Rate(records.Count(x => x.FinalPass), records.Count) + "\nBenchmark Path Match: " + (path ? "PASS" : "BENCHMARK_PATH_MISMATCH") + "\nCold Start Latency: " + (cold == null ? "N/A" : cold.Metrics.LatencyMs + " ms") + "\nWarm Average Latency: " + (warm.Count == 0 ? "N/A" : warm.Average(x => x.Metrics.LatencyMs).ToString("0") + " ms") + "\nMin / Max: " + records.Min(x => x.Metrics.LatencyMs) + " / " + records.Max(x => x.Metrics.LatencyMs) + " ms\nSlave RAM: " + records.Max(x => x.Metrics.ProcessWorkingSetMB) + " MB\nOllama RAM: " + records.Max(x => x.Metrics.OllamaWorkingSetMB) + " MB\nModel Memory / VRAM: " + records.Max(x => x.Metrics.ModelMemoryMB) + " / " + records.Max(x => x.Metrics.ModelVramMB) + " MB"; HybridSummary = BuildHybridSummary(records); StatusText = suite.Count + "건 상세 Benchmark 완료 · Task/GitHub 실행 0건";
            } finally { IsBusy = false; }
        }
        private IList<WorkTask> CandidateTasks() { List<WorkTask> values = new List<WorkTask>(); string[] lines = (Context ?? "").Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries); foreach (string line in lines) { string text = System.Text.RegularExpressions.Regex.Replace(line, @"^\s*\d+\.\s*", ""); string[] parts = text.Split(new[] { " - " }, StringSplitOptions.None); WorkTaskStatus status; if (!Enum.TryParse(parts.Length > 1 ? parts[parts.Length - 1].Replace(" ", "") : "Todo", true, out status)) status = WorkTaskStatus.Todo; values.Add(new WorkTask { Id = Guid.NewGuid(), Title = parts[0].Trim(), Status = status, CreatedAt = DateTime.Now, UpdatedAt = DateTime.Now }); } return values; }
        private static string Pass(bool value) { return value ? "PASS" : "FAIL"; } private static string Rate(int count, int total) { return total == 0 ? "0%" : (count * 100d / total).ToString("0.0") + "%"; }
        private static string BuildHybridSummary(IList<ParserComparisonRecord> records)
        {
            int both = records.Count(x => x.CurrentParserPass && x.FinalPass), parserOnly = records.Count(x => x.CurrentParserPass && !x.FinalPass), llmOnly = records.Count(x => !x.CurrentParserPass && x.FinalPass), neither = records.Count(x => !x.CurrentParserPass && !x.FinalPass), covered = records.Count(x => x.CurrentParserPass || x.FinalPass);
            int fallback = records.Count(x => x.HybridResult.FallbackCalled), fallbackSuccess = records.Count(x => x.HybridResult.FallbackCalled && x.HybridPass), unresolved = records.Count(x => x.HybridResult.Source == HybridCommandSource.UNRESOLVED), multi = records.Count(x => x.HybridResult.MultiActionSchemaLimit);
            StringBuilder text = new StringBuilder("Task-021 Hybrid Summary\nParser Accuracy: ").Append(Rate(records.Count(x => x.CurrentParserPass), records.Count)).Append("\nLLM Accuracy: ").Append(Rate(records.Count(x => x.FinalPass), records.Count)).Append("\nHybrid Accuracy: ").Append(Rate(records.Count(x => x.HybridPass), records.Count)).Append("\nOracle Hybrid Coverage: ").Append(Rate(covered, records.Count)).Append("\nParser Only: ").Append(records.Count - fallback).Append("\nLLM Fallback: ").Append(fallback).Append("\nFallback Success / Failure: ").Append(fallbackSuccess).Append(" / ").Append(fallback - fallbackSuccess).Append("\nUnresolved: ").Append(unresolved).Append("\nParser Avg Latency: ").Append(records.Average(x => x.HybridResult.ParserLatencyMs).ToString("0")).Append(" ms\nLLM Fallback Avg Latency: ").Append(fallback == 0 ? "N/A" : records.Where(x => x.HybridResult.FallbackCalled).Average(x => x.HybridResult.LlmResponse.LatencyMs).ToString("0") + " ms").Append("\nHybrid Avg Latency: ").Append(records.Average(x => x.HybridResult.HybridLatencyMs).ToString("0")).Append(" ms\nMulti Action Schema Limit: ").Append(multi).Append("\n\nHybrid Cross Analysis\nParser O / LLM O : ").Append(both).Append("\nParser O / LLM X : ").Append(parserOnly).Append("\nParser X / LLM O : ").Append(llmOnly).Append("\nParser X / LLM X : ").Append(neither);
            AppendGroup(text, "C. Parser X / LLM O — LLM 보완 문장", records.Where(x => !x.CurrentParserPass && x.FinalPass)); AppendGroup(text, "D. Parser X / LLM X — 미해결 문장", records.Where(x => !x.CurrentParserPass && !x.FinalPass)); return text.ToString();
        }
        private static void AppendGroup(StringBuilder text, string title, IEnumerable<ParserComparisonRecord> values) { text.Append("\n\n").Append(title); foreach (ParserComparisonRecord item in values) text.Append("\n").Append(item.No).Append(". ").Append(item.Input).Append(" | Expected ").Append(item.ExpectedIntent).Append(" ").Append("[").Append(string.Join(",", item.ExpectedTargets)).Append("] ").Append(item.ExpectedStatus ?? "null").Append(" | Parser ").Append(item.CurrentParserResult.Intent).Append(" [").Append(string.Join(",", item.CurrentParserResult.TargetIndexes)).Append("] ").Append(item.CurrentParserResult.Status ?? "null").Append(" | LLM ").Append(item.GraniteResult == null ? "SCHEMA/JSON FAIL" : item.GraniteResult.Intent + " [" + string.Join(",", item.GraniteResult.TargetIndexes) + "] " + (item.GraniteResult.Status ?? "null")); }
        private static List<TestCase> Cases() { return new List<TestCase> { T("업무 보여줘","READ_TASK"),T("오늘 업무 알려줘","READ_TASK"),T("오늘 나의 일정 알려줘","READ_TASK"),T("오늘 MCC 로그 분석 업무 등록해줘","CREATE_TASK",title:"MCC 로그 분석"),T(RegressionInput,"UPDATE_TASK",new[]{2},"Done"),T("2번 Done으로 바꿔줘","UPDATE_TASK",new[]{2},"Done"),T("2번만 Done으로 바꿔줘","UPDATE_TASK",new[]{2},"Done"),T("2번하고 3번 완료해줘","UPDATE_TASK",new[]{2,3},"Done"),T("두 번째 업무 완료해줘","UPDATE_TASK",new[]{2},"Done"),T("두 번째 것만 끝난 걸로 해줘","UPDATE_TASK",new[]{2},"Done"),T("방금 등록한 업무 진행중으로 바꿔줘","UPDATE_TASK",null,"InProgress",reference:"LAST_CREATED"),T("아까 등록한 거 완료해줘","UPDATE_TASK",null,"Done",reference:"LAST_CREATED"),T("방금 만든 거 보여줘","READ_TASK",reference:"LAST_CREATED"),T("FMP 업무 보여줘","READ_TASK",keyword:"FMP"),T("FMP 관련 업무 알려줘","READ_TASK",keyword:"FMP"),T("FMP 관련해서 아직 안 끝난 업무 보여줘","READ_TASK",keyword:"FMP"),T("아까 하던 FMP 그거 이제 끝난 걸로 해놓자","UPDATE_TASK",null,"Done",keyword:"FMP"),T("오늘 해야 하는 거 뭐 남았냐","READ_TASK"),T("지금 내가 하고 있는 업무 뭐야","READ_TASK"),T("두 번째 건은 끝났고 첫 번째 건은 아직 하는 중이야","UPDATE_TASK",new[]{1,2},null) }; }
        private static TestCase T(string i,string intent,int[] targets=null,string status=null,string keyword=null,string reference=null,string title=null) { return new TestCase { Input=i,Intent=intent,Targets=targets??new int[0],Status=status,Keyword=keyword,Reference=reference,Title=title }; } private sealed class TestCase { public string Input; public string Intent; public IList<int> Targets=new List<int>(); public string Status; public string Keyword; public string Reference; public string Title; }
    }
    public sealed class BenchmarkRow
    {
        public BenchmarkRow(ParserComparisonRecord r) { No=r.No; Input=r.Input; ExpectedIntent=r.ExpectedIntent; ExpectedTargets=Join(r.ExpectedTargets); ExpectedStatus=r.ExpectedStatus; Expected=Compact(r.ExpectedIntent,r.ExpectedTargets,r.ExpectedStatus); CurrentIntent=r.CurrentParserResult.Intent; CurrentTargets=Join(r.CurrentParserResult.TargetIndexes); CurrentStatus=r.CurrentParserResult.Status; ParserResult=Compact(CurrentIntent,r.CurrentParserResult.TargetIndexes,CurrentStatus); CurrentPass=Flag(r.CurrentParserPass); GraniteRaw=r.GraniteRawResponse; GraniteIntent=r.GraniteResult==null?null:r.GraniteResult.Intent; GraniteTargets=r.GraniteResult==null?null:Join(r.GraniteResult.TargetIndexes); GraniteStatus=r.GraniteResult==null?null:r.GraniteResult.Status; LlmResult=r.GraniteResult==null?"SCHEMA/JSON FAIL":Compact(GraniteIntent,r.GraniteResult.TargetIndexes,GraniteStatus); HybridResult=r.HybridResult.Result==null?"NEEDS_CLARIFICATION":Compact(r.HybridResult.Result.Intent,r.HybridResult.Result.TargetIndexes,r.HybridResult.Result.Status); HybridSource=r.HybridResult.Source.ToString(); DecisionReason=r.HybridResult.Reason; FallbackCalled=r.HybridResult.FallbackCalled?"YES":"NO"; HybridPass=Flag(r.HybridPass); JsonPass=Flag(r.JsonPass); SchemaPass=Flag(r.SchemaPass); SemanticPass=Flag(r.SemanticPass); EvaluationPass=Flag(r.EvaluationPass); FinalPass=r.BenchmarkPathMatch?Flag(r.FinalPass):"BENCHMARK_PATH_MISMATCH"; Group=r.CurrentParserPass?(r.FinalPass?"A. Parser O / LLM O":"B. Parser O / LLM X"):(r.FinalPass?"C. Parser X / LLM O":"D. Parser X / LLM X"); LatencyMs=r.HybridResult.HybridLatencyMs; ColdStart=r.Metrics.ColdStart?"COLD":"WARM"; Failure=r.FailureKind; }
        private static string Join(IEnumerable<int> x){return "["+string.Join(",",x??new int[0])+"]";} private static string Flag(bool x){return x?"PASS":"FAIL";} private static string Compact(string intent,IEnumerable<int> targets,string status){return (intent??"UNKNOWN")+" "+Join(targets)+" "+(status??"null");}
        public int No{get;set;} public string Input{get;set;} public string Expected{get;set;} public string ParserResult{get;set;} public string LlmResult{get;set;} public string HybridResult{get;set;} public string HybridSource{get;set;} public string DecisionReason{get;set;} public string FallbackCalled{get;set;} public string HybridPass{get;set;} public string Group{get;set;} public string ExpectedIntent{get;set;} public string ExpectedTargets{get;set;} public string ExpectedStatus{get;set;} public string CurrentIntent{get;set;} public string CurrentTargets{get;set;} public string CurrentStatus{get;set;} public string CurrentPass{get;set;} public string GraniteRaw{get;set;} public string GraniteIntent{get;set;} public string GraniteTargets{get;set;} public string GraniteStatus{get;set;} public string JsonPass{get;set;} public string SchemaPass{get;set;} public string SemanticPass{get;set;} public string EvaluationPass{get;set;} public string FinalPass{get;set;} public long LatencyMs{get;set;} public string ColdStart{get;set;} public string Failure{get;set;}
    }
}
