using System.Collections.Generic;
using System.Linq;
using System.Windows.Input;
using SlaveSplit.Agents;
using SlaveSplit.Commands;
using SlaveSplit.Infrastructure;
using SlaveSplit.Models;
using SlaveSplit.Repositories;
using SlaveSplit.Services;
using SlaveSplit.Services.AI;
using SlaveSplit.Services.GitHub;
namespace SlaveSplit.ViewModels
{
    public sealed class MainViewModel : ViewModelBase
    {
        private TaskBoardViewModel board;
        private readonly TaskService taskService; private readonly ConversationService conversationService; private readonly TaskNavigationService taskNavigation; private readonly DashboardNavigationService dashboardNavigation; private readonly DailySummaryService dailySummaries; private readonly IGitHubIssueCreationService githubCreation; private readonly IGitHubSyncService githubSync; private readonly Stack<ViewModelBase> detailHistory = new Stack<ViewModelBase>(); private readonly WorkspaceService workspaceService; private readonly GitHubSettingsService gitHubSettingsService; private readonly GitHubSettings gitHubSettings; private AgentConversationService conversationAgent; private ViewModelBase currentViewModel; private string selectedNavigation;
        public MainViewModel()
        {
            SystemClock clock = new SystemClock(); gitHubSettingsService=new GitHubSettingsService();gitHubSettings=gitHubSettingsService.Load();workspaceService=new WorkspaceService(null,gitHubSettings);taskService = new TaskService(new WorkspaceTaskRepository(new LocalTaskRepository(),workspaceService), clock); conversationService = new ConversationService(new LocalConversationRepository(), clock); taskNavigation = new TaskNavigationService(); dashboardNavigation = new DashboardNavigationService(); dailySummaries = new DailySummaryService(taskService, clock); UserSettingsService userSettings = new UserSettingsService(); AiProviderOptions options = new AiProviderOptions(); MockAiProvider mock = new MockAiProvider(); CompanyAiProvider company = new CompanyAiProvider(options, new EnvironmentCredentialProvider("SLAVESPLIT_AI_TOKEN")); AiProviderManager providers = new AiProviderManager(options, mock, company); AgentLogger logger = new AgentLogger(); ConversationContext agentContext = new ConversationContext(); RuleBasedAgentService rule = new RuleBasedAgentService(taskService, agentContext, clock, logger, dailySummaries); IAiContextBuilder contextBuilder = new AiContextBuilder(taskService, clock, options, PromptLoader.LoadSlaveAgentPrompt()); IAgentService agent;
            GitHubStatus = new GitHubStatusService(); IGitHubCredentialProvider credentials = new WindowsGitHubCredentialProvider(); IGitHubService gitHub = new GitHubService(new GitHubClient(), credentials, GitHubStatus); GitHubNavigationService gitHubNavigation = new GitHubNavigationService(); IGitHubTaskMappingService mappings = new GitHubTaskMappingService(taskService); IGitHubProjectService projectService = new GitHubProjectService(new GitHubClient(), credentials); GitHubIssueCreationService creation = new GitHubIssueCreationService(gitHub, gitHubSettingsService, mappings); githubCreation = creation; githubSync = new GitHubSyncService(taskService, gitHub, gitHubSettingsService, null, projectService); creation.ProjectSyncService = githubSync; taskService.GitHubCreationService = githubCreation; taskService.GitHubSyncService = githubSync; string[] toolNames = { "create_task", "get_today_tasks", "get_recent_tasks", "search_tasks", "get_task", "start_task", "complete_task", "reopen_task", "block_task", "add_task_memo", "update_task_description","update_task_due_date", "get_task_github_status", "create_github_issue", "retry_github_sync", "get_recent_history", "delete_task", "delete_tasks", "refresh_github_issues", "import_github_issue" }; AgentToolRegistry toolRegistry = new AgentToolRegistry(toolNames.Select(x => (IAgentTool)new WorkTaskAgentTool(x, taskService, githubCreation, githubSync, clock, gitHub, gitHubSettingsService, mappings))); AgentToolExecutor toolExecutor = new AgentToolExecutor(toolRegistry, agentContext, logger); conversationAgent = new AgentConversationService(providers, contextBuilder, toolExecutor, taskService, agentContext, rule, options, logger, clock,null,false,null,workspaceService);agent=conversationAgent; ConversationContext benchmarkContext = new ConversationContext(); RuleBasedAgentService benchmarkRule = new RuleBasedAgentService(taskService, benchmarkContext, clock, logger, dailySummaries); AgentToolExecutor benchmarkExecutor = new AgentToolExecutor(toolRegistry, benchmarkContext, logger); AgentConversationService benchmarkAgent = new AgentConversationService(providers, contextBuilder, benchmarkExecutor, taskService, benchmarkContext, benchmarkRule, options, logger, clock); GitHubStatus.StatusChanged += delegate { OnPropertyChanged("GitHubHeaderText"); OnPropertyChanged("IsGitHubConnected"); };
            toolRegistry.Register(new WorkTaskAgentTool("update_task_priority",taskService,githubCreation,githubSync,clock,gitHub,gitHubSettingsService,mappings));toolRegistry.Register(new WorkTaskAgentTool("work_briefing",taskService,githubCreation,githubSync,clock,gitHub,gitHubSettingsService,mappings));Chat = new ChatViewModel(taskService, agent, conversationService, providers, taskNavigation); Today = new TodayViewModel(taskService, taskNavigation, dashboardNavigation, dailySummaries, clock); Tasks = new TasksViewModel(taskService, taskNavigation); History = new HistoryViewModel(conversationService, taskNavigation); Weekly = new WeeklyReportViewModel(new WeeklySummaryService(taskService), new WorkReportFormatter(taskService), clock); GitHubIssues = new GitHubViewModel(gitHub, gitHubSettings, gitHubNavigation, mappings, githubSync); Settings = new SettingsViewModel(providers, userSettings, gitHub, gitHubSettingsService, credentials, projectService,workspaceService); LocalLlm = new LocalLlmPocViewModel(taskService, benchmarkAgent); AgentTests = new AgentTestRunnerViewModel();
            workspaceService.ActiveWorkspaceChanged+=OnWorkspaceChanged;workspaceService.WorkspacesChanged+=delegate{OnPropertyChanged("Workspaces");};taskNavigation.OpenRequested += OnOpenTask; taskNavigation.BackRequested += OnBack; dashboardNavigation.DailySummaryRequested += OnDailySummary; gitHubNavigation.IssueRequested += delegate(object sender, GitHubIssueNavigationEventArgs e) { if (CurrentViewModel != null) detailHistory.Push(CurrentViewModel); CurrentViewModel = new GitHubIssueDetailViewModel(e.Number, gitHub, gitHubSettings, gitHubNavigation, mappings, taskNavigation); }; gitHubNavigation.BackRequested += OnBack; gitHubNavigation.SettingsRequested += delegate { Navigate("Settings"); };
            toolRegistry.Register(new WorkTaskAgentTool("update_task_time",taskService,githubCreation,githubSync,clock,gitHub,gitHubSettingsService,mappings));toolRegistry.Register(new WorkTaskAgentTool("update_task_reminder",taskService,githubCreation,githubSync,clock,gitHub,gitHubSettingsService,mappings));NavigateCommand = new RelayCommand(Navigate); QuickAddCommand = new RelayCommand(p => { Navigate("Today"); Today.IsAddPanelOpen = true; }); FocusChatCommand = new RelayCommand(p => Navigate("Chat")); BackCommand = new RelayCommand(p => OnBack(this, System.EventArgs.Empty)); Navigate(userSettings.Load().StartupPage);
        }
        public GitHubStatusService GitHubStatus { get; private set; } public string GitHubHeaderText { get { return GitHubStatus == null ? "○ GitHub" : GitHubStatus.HeaderText; } } public bool IsGitHubConnected { get { return GitHubStatus != null && GitHubStatus.Status == GitHubConnectionStatus.Connected; } } public ChatViewModel Chat { get; private set; } public TodayViewModel Today { get; private set; } public TasksViewModel Tasks { get; private set; } public HistoryViewModel History { get; private set; } public WeeklyReportViewModel Weekly { get; private set; } public GitHubViewModel GitHubIssues { get; private set; } public SettingsViewModel Settings { get; private set; } public LocalLlmPocViewModel LocalLlm { get; private set; } public AgentTestRunnerViewModel AgentTests { get; private set; } public ICommand NavigateCommand { get; private set; } public ICommand QuickAddCommand { get; private set; } public ICommand FocusChatCommand { get; private set; } public ICommand BackCommand { get; private set; }
        public TaskBoardViewModel Board { get { return board ?? (board=new TaskBoardViewModel(taskService,taskNavigation,()=>workspaceService.CurrentScopeId)); } }
        public IList<GitHubWorkspace> Workspaces { get { return workspaceService.Workspaces; } } public GitHubWorkspace SelectedWorkspace { get { return workspaceService.ActiveWorkspace; } set { if(value!=null&&value.Id!=workspaceService.ActiveWorkspace.Id)ChangeWorkspace(value); } }
        public ViewModelBase CurrentViewModel { get { return currentViewModel; } private set { SetProperty(ref currentViewModel, value); } } public string SelectedNavigation { get { return selectedNavigation; } private set { SetProperty(ref selectedNavigation, value); } }
        private void Navigate(object parameter) { string page = parameter as string; SelectedNavigation = page; detailHistory.Clear(); switch (page) { case "Today": CurrentViewModel = Today; break; case "Tasks": CurrentViewModel = Tasks; break; case "Board": CurrentViewModel = Board; break; case "History": CurrentViewModel = History; break; case "Weekly": CurrentViewModel = Weekly; break; case "GitHub": CurrentViewModel = GitHubIssues; break; case "LocalLlm": CurrentViewModel = LocalLlm; break; case "AgentTests": CurrentViewModel = AgentTests; break; case "Settings": CurrentViewModel = Settings; break; default: CurrentViewModel = Chat; break; } }
        private void OnOpenTask(object sender, TaskNavigationEventArgs e) { if (CurrentViewModel != null) detailHistory.Push(CurrentViewModel); CurrentViewModel = new TaskDetailViewModel(e.TaskId, taskService, conversationService, taskNavigation) { GitHubCreationService = githubCreation, GitHubSyncService = githubSync }; }
        private void OnDailySummary(object sender, DailySummaryNavigationEventArgs e) { if (CurrentViewModel != null) detailHistory.Push(CurrentViewModel); CurrentViewModel = new DailySummaryViewModel(dailySummaries, null, e.Date); }
        private void OnBack(object sender, System.EventArgs e) { CurrentViewModel = detailHistory.Count > 0 ? detailHistory.Pop() : (ViewModelBase)Tasks; }
        private void ChangeWorkspace(GitHubWorkspace value){workspaceService.SetActive(value);}
        private async void OnWorkspaceChanged(object sender,WorkspaceChangedEventArgs e){GitHubWorkspace value=e.Workspace;gitHubSettings.Owner=value.Owner;gitHubSettings.Repository=value.Repository;gitHubSettings.ProjectId=value.ProjectId;gitHubSettingsService.Save(gitHubSettings);conversationAgent.ResetContext();GitHubIssues.ResetCache();OnPropertyChanged("SelectedWorkspace");await Today.LoadAsync();await Tasks.LoadAsync();if(board!=null)await board.LoadAsync();await GitHubIssues.LoadAsync(true);}
    }
}
