using System;
using System.Linq;
using System.Collections.ObjectModel;
using System.Threading;
using System.Windows.Input;
using SlaveSplit.Commands;
using SlaveSplit.Services.AI;
using SlaveSplit.Services.GitHub;
using SlaveSplit.Models;
using SlaveSplit.Services;
namespace SlaveSplit.ViewModels
{
    public sealed class SettingsViewModel : ViewModelBase
    {
        private readonly AiProviderManager manager; private readonly SlaveSplit.Services.UserSettingsService settingsService; private readonly SlaveSplit.Services.UserSettings settings; private readonly IGitHubService gitHub; private readonly GitHubSettingsService gitHubSettingsService; private readonly IGitHubCredentialProvider gitHubCredentials; private readonly GitHubSettings gitHubSettings; private readonly IGitHubProjectService projectService; private readonly WorkspaceService workspaceService; private string connectionResult, gitHubResult, tokenInput, projectResult,workspaceDisplayName,workspaceOwner,workspaceRepository; private bool isTesting, isGitHubTesting, hasStoredGitHubCredential; private GitHubRepositoryInfo gitHubRepository; private GitHubProjectInfo selectedProject; private GitHubProjectStatusField selectedStatusField;
        public SettingsViewModel(AiProviderManager manager, SlaveSplit.Services.UserSettingsService settingsService = null, IGitHubService gitHub = null, GitHubSettingsService gitHubSettingsService = null, IGitHubCredentialProvider gitHubCredentials = null, IGitHubProjectService projectService = null,WorkspaceService workspaceService=null) { this.manager = manager; this.settingsService = settingsService ?? new SlaveSplit.Services.UserSettingsService(); settings = this.settingsService.Load(); this.gitHubSettingsService = gitHubSettingsService ?? new GitHubSettingsService(); this.gitHubCredentials = gitHubCredentials ?? new WindowsGitHubCredentialProvider(); this.gitHub = gitHub ?? new GitHubService(new GitHubClient(), this.gitHubCredentials); this.projectService = projectService ?? new GitHubProjectService(new GitHubClient(), this.gitHubCredentials);this.workspaceService=workspaceService; gitHubSettings = this.gitHubSettingsService.Load(); HasStoredGitHubCredential = this.gitHubCredentials.HasToken(); GitHubResult = HasStoredGitHubCredential ? "Stored credential ready. Test connection to verify GitHub." : "No stored GitHub credential."; Projects = new ObservableCollection<GitHubProjectInfo>(); StatusFields = new ObservableCollection<GitHubProjectStatusField>();Workspaces=new ObservableCollection<GitHubWorkspace>(workspaceService==null?new GitHubWorkspace[0]:workspaceService.Workspaces); ProviderKinds = Enum.GetValues(typeof(AiProviderKind)).Cast<AiProviderKind>().ToArray(); StartupPages = new[] { "Today", "Chat" }; TestConnectionCommand = new RelayCommand(async p => await TestAsync(), p => !IsTesting); TestGitHubCommand = new RelayCommand(async p => await TestGitHubAsync(), p => !IsGitHubTesting); TestProjectCommand = new RelayCommand(async p => await LoadProjectsAsync()); OpenGitHubCommand = new RelayCommand(p => OpenGitHub(), p => CanOpenGitHub);AddWorkspaceCommand=new RelayCommand(p=>AddWorkspace(),p=>workspaceService!=null&&!string.IsNullOrWhiteSpace(WorkspaceDisplayName)&&!string.IsNullOrWhiteSpace(WorkspaceOwner)&&!string.IsNullOrWhiteSpace(WorkspaceRepository)); }
        public AiProviderKind[] ProviderKinds { get; private set; }
        public string[] StartupPages { get; private set; } public string StartupPage { get { return settings.StartupPage; } set { settings.StartupPage = value == "Chat" ? "Chat" : "Today"; settingsService.Save(settings); OnPropertyChanged(); } }
        public bool AdminMode { get { return settings.AdminMode; } set { settings.AdminMode=value;settingsService.Save(settings);OnPropertyChanged(); } }
        public AiProviderKind SelectedProvider { get { return manager.Options.Provider; } set { manager.Select(value); OnPropertyChanged(); OnPropertyChanged("StatusText"); } }
        public string Endpoint { get { return manager.Options.Endpoint; } set { manager.Options.Endpoint = value; OnPropertyChanged(); } } public string Model { get { return manager.Options.Model; } set { manager.Options.Model = value; OnPropertyChanged(); } }
        public int TimeoutSeconds { get { return manager.Options.TimeoutSeconds; } set { manager.Options.TimeoutSeconds = Math.Max(1, value); OnPropertyChanged(); } } public string StatusText { get { return manager.Current.Status.ToString(); } }
        public string ConnectionResult { get { return connectionResult; } private set { SetProperty(ref connectionResult, value); } } public bool IsTesting { get { return isTesting; } private set { if (SetProperty(ref isTesting, value)) System.Windows.Input.CommandManager.InvalidateRequerySuggested(); } }
        public bool GitHubEnabled { get { return gitHubSettings.Enabled; } set { gitHubSettings.Enabled = value; SaveGitHubSettings(); OnPropertyChanged(); } } public string GitHubOwner { get { return gitHubSettings.Owner; } set { gitHubSettings.Owner = value; SaveGitHubSettings(); OnPropertyChanged(); } } public string GitHubRepositoryName { get { return gitHubSettings.Repository; } set { gitHubSettings.Repository = value; SaveGitHubSettings(); OnPropertyChanged(); } } public int GitHubTimeoutSeconds { get { return gitHubSettings.TimeoutSeconds; } set { gitHubSettings.TimeoutSeconds = Math.Max(1, value); SaveGitHubSettings(); OnPropertyChanged(); } }
        public bool GitHubAutoCreateIssues { get { return gitHubSettings.AutoCreateIssues; } set { gitHubSettings.AutoCreateIssues = value; SaveGitHubSettings(); OnPropertyChanged(); } }
        public bool GitHubProjectSyncEnabled { get { return gitHubSettings.ProjectSyncEnabled; } set { gitHubSettings.ProjectSyncEnabled = value; SaveGitHubSettings(); OnPropertyChanged(); } } public ObservableCollection<GitHubProjectInfo> Projects { get; private set; } public ObservableCollection<GitHubProjectStatusField> StatusFields { get; private set; } public string ProjectResult { get { return projectResult; } private set { SetProperty(ref projectResult, value); } }
        public GitHubProjectInfo SelectedProject { get { return selectedProject; } set { if (!SetProperty(ref selectedProject, value) || value == null) return; gitHubSettings.ProjectId = value.Id; gitHubSettings.ProjectTitle = value.Title; StatusFields.Clear(); foreach (GitHubProjectStatusField field in value.StatusFields) StatusFields.Add(field); SelectedStatusField = StatusFields.FirstOrDefault(x => string.Equals(x.Name, "Status", StringComparison.OrdinalIgnoreCase)) ?? StatusFields.FirstOrDefault(); SaveGitHubSettings(); } }
        public GitHubProjectStatusField SelectedStatusField { get { return selectedStatusField; } set { if (!SetProperty(ref selectedStatusField, value) || value == null) return; gitHubSettings.StatusFieldId = value.Id; gitHubSettings.TodoOptionId = Option(value, "Todo"); gitHubSettings.InProgressOptionId = Option(value, "In Progress"); gitHubSettings.DoneOptionId = Option(value, "Done"); gitHubSettings.BlockedOptionId = Option(value, "Blocked"); SaveGitHubSettings(); } }
        public string GitHubTokenInput { get { return tokenInput; } set { SetProperty(ref tokenInput, value); } } public bool HasStoredGitHubCredential { get { return hasStoredGitHubCredential; } private set { if (SetProperty(ref hasStoredGitHubCredential, value)) OnPropertyChanged("GitHubCredentialStatusText"); } } public string GitHubCredentialStatusText { get { return HasStoredGitHubCredential ? "Credential stored in Windows Credential Manager" : "No stored GitHub credential"; } } public string GitHubResult { get { return gitHubResult; } private set { SetProperty(ref gitHubResult, value); } } public bool IsGitHubTesting { get { return isGitHubTesting; } private set { if (SetProperty(ref isGitHubTesting, value)) CommandManager.InvalidateRequerySuggested(); OnPropertyChanged("GitHubButtonText"); } } public string GitHubButtonText { get { return IsGitHubTesting ? "Connecting..." : "Test Connection"; } } public GitHubRepositoryInfo GitHubRepository { get { return gitHubRepository; } private set { SetProperty(ref gitHubRepository, value); OnPropertyChanged("HasGitHubRepository"); OnPropertyChanged("CanOpenGitHub"); CommandManager.InvalidateRequerySuggested(); } } public bool HasGitHubRepository { get { return GitHubRepository != null; } } public bool CanOpenGitHub { get { Uri uri; return GitHubRepository != null && Uri.TryCreate(GitHubRepository.HtmlUrl, UriKind.Absolute, out uri) && uri.Scheme == Uri.UriSchemeHttps && string.Equals(uri.Host, "github.com", StringComparison.OrdinalIgnoreCase); } }
        public ICommand TestConnectionCommand { get; private set; } public ICommand TestGitHubCommand { get; private set; } public ICommand TestProjectCommand { get; private set; } public ICommand OpenGitHubCommand { get; private set; }
        public ObservableCollection<GitHubWorkspace> Workspaces{get;private set;}public string WorkspaceDisplayName{get{return workspaceDisplayName;}set{SetProperty(ref workspaceDisplayName,value);CommandManager.InvalidateRequerySuggested();}}public string WorkspaceOwner{get{return workspaceOwner;}set{SetProperty(ref workspaceOwner,value);CommandManager.InvalidateRequerySuggested();}}public string WorkspaceRepository{get{return workspaceRepository;}set{SetProperty(ref workspaceRepository,value);CommandManager.InvalidateRequerySuggested();}}public ICommand AddWorkspaceCommand{get;private set;}
        private void AddWorkspace(){if(workspaceService.Workspaces.Any(x=>string.Equals(x.DisplayName,WorkspaceDisplayName,StringComparison.OrdinalIgnoreCase))){GitHubResult="Workspace name already exists.";return;}var item=new GitHubWorkspace{DisplayName=WorkspaceDisplayName.Trim(),Owner=WorkspaceOwner.Trim(),Repository=WorkspaceRepository.Trim(),CredentialProfileId=WorkspaceService.DefaultCredentialId,IsEnabled=true};workspaceService.Add(item);Workspaces.Add(item);WorkspaceDisplayName=WorkspaceOwner=WorkspaceRepository="";GitHubResult="Workspace added. It reuses the selected credential profile.";}
        private async System.Threading.Tasks.Task TestAsync() { IsTesting = true; ConnectionResult = "Checking..."; try { using (CancellationTokenSource timeout = new CancellationTokenSource(TimeSpan.FromSeconds(TimeoutSeconds))) { AiResponse response = await manager.TestConnectionAsync(timeout.Token); ConnectionResult = response.Success ? "Connected · Response " + response.ElapsedMilliseconds + " ms" : "Connection Failed · " + response.ErrorMessage; OnPropertyChanged("StatusText"); } } catch (Exception ex) { ConnectionResult = "Connection Failed · " + ex.Message; } finally { IsTesting = false; } }
        private async System.Threading.Tasks.Task TestGitHubAsync() { IsGitHubTesting = true; GitHubResult = "Connecting..."; GitHubRepository = null; try { if (!string.IsNullOrWhiteSpace(GitHubTokenInput)) { if (!gitHubCredentials.SaveToken(GitHubTokenInput.Trim())) { HasStoredGitHubCredential = gitHubCredentials.HasToken(); GitHubResult = "GitHub credential could not be saved."; return; } GitHubTokenInput = ""; HasStoredGitHubCredential = true; } else { HasStoredGitHubCredential = gitHubCredentials.HasToken(); } GitHubConnectionResult result = await gitHub.TestConnectionAsync(gitHubSettings, CancellationToken.None); GitHubResult = result.Success ? "Connected · " + result.ElapsedMilliseconds + " ms" : result.Message; GitHubRepository = result.Repository; if (result.Success && !gitHubSettings.Enabled) { gitHubSettings.Enabled = true; SaveGitHubSettings(); OnPropertyChanged("GitHubEnabled"); } } catch { GitHubResult = "GitHub connection failed."; } finally { IsGitHubTesting = false; } }
        private void SaveGitHubSettings() { try { gitHubSettingsService.Save(gitHubSettings); } catch { GitHubResult = "GitHub settings could not be saved."; } }
        private async System.Threading.Tasks.Task LoadProjectsAsync() { ProjectResult = "Loading projects..."; GitHubProjectsResult result = await projectService.GetProjectsAsync(GitHubOwner, CancellationToken.None); Projects.Clear(); if (!result.Success) { ProjectResult = result.Message; return; } foreach (GitHubProjectInfo project in result.Projects) Projects.Add(project); SelectedProject = Projects.FirstOrDefault(x => x.Id == gitHubSettings.ProjectId) ?? Projects.FirstOrDefault(); ProjectResult = Projects.Count + " project(s) loaded."; }
        private static string Option(GitHubProjectStatusField field, string name) { GitHubProjectStatusOption option = field.Options.FirstOrDefault(x => string.Equals(x.Name, name, StringComparison.OrdinalIgnoreCase)); return option == null ? null : option.Id; }
        private void OpenGitHub() { if (!CanOpenGitHub) return; try { System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(GitHubRepository.HtmlUrl) { UseShellExecute = true }); } catch { GitHubResult = "Could not open GitHub."; } }
    }
}
