using System; using System.Collections.ObjectModel; using System.Linq; using System.Windows.Input; using SlaveSplit.Commands; using SlaveSplit.Models; using SlaveSplit.Services;
namespace SlaveSplit.ViewModels
{
    public sealed class TasksViewModel : ViewModelBase
    {
        private readonly TaskService service; private readonly TaskNavigationService navigation; private string searchText, selectedFilter = "All", selectedSort = "Updated";
        public TasksViewModel(TaskService service, TaskNavigationService navigation) { this.service = service; this.navigation = navigation; Tasks = new ObservableCollection<WorkTask>(); Filters = new[] { "All", "Todo", "In Progress", "Blocked", "Done" }; SortOptions = new[] { "Updated", "Created", "Due Date", "Priority" }; SearchCommand = new RelayCommand(async p => await LoadAsync()); FilterCommand = new RelayCommand(async p => { SelectedFilter = p as string; await LoadAsync(); }); OpenTaskCommand = new RelayCommand(p => { WorkTask task = p as WorkTask; if (task != null) navigation.Open(task.Id); }); service.TasksChanged += async (s, e) => await LoadAsync(); Initialize(); }
        public ObservableCollection<WorkTask> Tasks { get; private set; } public string[] Filters { get; private set; } public string[] SortOptions { get; private set; } public string SearchText { get { return searchText; } set { SetProperty(ref searchText, value); } } public string SelectedFilter { get { return selectedFilter; } set { SetProperty(ref selectedFilter, value); } } public string SelectedSort { get { return selectedSort; } set { if (SetProperty(ref selectedSort, value)) Initialize(); } } public bool IsEmpty { get { return Tasks.Count == 0; } }
        public ICommand SearchCommand { get; private set; } public ICommand FilterCommand { get; private set; } public ICommand OpenTaskCommand { get; private set; }
        public async System.Threading.Tasks.Task LoadAsync() { var query = (await service.GetAllAsync()).AsEnumerable(); if (!string.IsNullOrWhiteSpace(SearchText)) { string value = SearchText.Trim(); query = query.Where(x => (x.Title ?? "").IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0 || (x.Description ?? "").IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0 || (x.Category ?? "").IndexOf(value, StringComparison.OrdinalIgnoreCase) >= 0); } if (SelectedFilter == "Todo") query = query.Where(x => x.Status == WorkTaskStatus.Todo); else if (SelectedFilter == "In Progress") query = query.Where(x => x.Status == WorkTaskStatus.InProgress); else if (SelectedFilter == "Blocked") query = query.Where(x => x.Status == WorkTaskStatus.Blocked); else if (SelectedFilter == "Done") query = query.Where(x => x.Status == WorkTaskStatus.Done); if (SelectedSort == "Created") query = query.OrderByDescending(x => x.CreatedAt); else if (SelectedSort == "Due Date") query = query.OrderBy(x => x.DueDate ?? DateTime.MaxValue); else if (SelectedSort == "Priority") query = query.OrderByDescending(x => x.Priority); else query = query.OrderByDescending(x => x.UpdatedAt); Tasks.Clear(); foreach (WorkTask item in query) Tasks.Add(item); OnPropertyChanged("IsEmpty"); }
        private async void Initialize() { await LoadAsync(); }
    }
}
