using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Windows.Input;
using SlaveSplit.Commands;
using SlaveSplit.Models;
using SlaveSplit.Services;
using SlaveSplit.Services.GitHub;
namespace SlaveSplit.ViewModels
{
    public sealed class TimelineItemViewModel
    {
        public TaskHistory History { get; set; } public bool ShowDate { get; set; } public string DateText { get { return History.CreatedAt.ToString("MMM dd, yyyy").ToUpperInvariant(); } } public string TimeText { get { return History.CreatedAt.ToString("HH:mm"); } }
        public string Title { get { switch (History.ActionType) { case TaskHistoryAction.Created: return "업무 등록"; case TaskHistoryAction.Started: return "업무 시작"; case TaskHistoryAction.Completed: return "업무 완료"; case TaskHistoryAction.Blocked: return "업무 대기"; case TaskHistoryAction.Unblocked: return "업무 대기 해제"; case TaskHistoryAction.MemoAdded: return "메모"; case TaskHistoryAction.FollowUpCreated: return "후속 업무 생성"; case TaskHistoryAction.CreatedFromTask: return "원본 업무에서 생성"; case TaskHistoryAction.GitHubSynced: return "GitHub 동기화"; default: return "업무 수정"; } } }
        public string Memo { get { return History.Memo; } }
    }
    public sealed class TaskDetailViewModel : ViewModelBase
    {
        private readonly Guid taskId; private readonly TaskService tasks; private readonly ConversationService conversations; private readonly TaskNavigationService navigation; private WorkTask task, parentTask; private string noteText, blockReason, errorMessage, githubMessage; private bool isEditing, isCreatingGitHubIssue, isSyncingGitHub; public IGitHubIssueCreationService GitHubCreationService { private get; set; } public IGitHubSyncService GitHubSyncService { private get; set; }
        public TaskDetailViewModel(Guid taskId, TaskService tasks, ConversationService conversations, TaskNavigationService navigation)
        {
            this.taskId = taskId; this.tasks = tasks; this.conversations = conversations; this.navigation = navigation; Timeline = new ObservableCollection<TimelineItemViewModel>(); FollowUps = new ObservableCollection<WorkTask>(); RelatedMessages = new ObservableCollection<Message>(); Priorities = Enum.GetValues(typeof(TaskPriority)).Cast<TaskPriority>().ToArray(); BackCommand = new RelayCommand(p => navigation.Back()); AddNoteCommand = new RelayCommand(async p => await AddNoteAsync(), p => Task != null && !string.IsNullOrWhiteSpace(NoteText)); StartCommand = new RelayCommand(async p => await ChangeAsync(() => tasks.StartAsync(Task))); CompleteCommand = new RelayCommand(async p => await ChangeAsync(() => tasks.CompleteAsync(Task))); BlockCommand = new RelayCommand(async p => await ChangeAsync(() => tasks.BlockAsync(Task, BlockReason)), p => !string.IsNullOrWhiteSpace(BlockReason)); UnblockCommand = new RelayCommand(async p => await ChangeAsync(() => tasks.UnblockAsync(Task, false))); TodoCommand = new RelayCommand(async p => await ChangeAsync(() => tasks.MoveToTodoAsync(Task))); ToggleEditCommand = new RelayCommand(p => IsEditing = !IsEditing); SaveCommand = new RelayCommand(async p => await SaveAsync()); OpenTaskCommand = new RelayCommand(p => { WorkTask item = p as WorkTask; if (item != null) navigation.Open(item.Id); }); OpenParentCommand = new RelayCommand(p => { if (ParentTask != null) navigation.Open(ParentTask.Id); }); OpenGitHubCommand = new RelayCommand(p => OpenGitHub(), p => CanOpenGitHub); Initialize();
        }
        public WorkTask Task { get { return task; } private set { SetProperty(ref task, value); NotifyTask(); } } public WorkTask ParentTask { get { return parentTask; } private set { SetProperty(ref parentTask, value); OnPropertyChanged("HasParent"); } }
        public ObservableCollection<TimelineItemViewModel> Timeline { get; private set; } public ObservableCollection<WorkTask> FollowUps { get; private set; } public ObservableCollection<Message> RelatedMessages { get; private set; } public TaskPriority[] Priorities { get; private set; }
        public bool HasParent { get { return ParentTask != null; } } public bool HasHistory { get { return Timeline.Count > 0; } } public bool IsBlocked { get { return Task != null && Task.Status == WorkTaskStatus.Blocked; } } public bool IsGitHubTask { get { return Task != null && Task.Source == TaskSource.GitHub && !string.IsNullOrWhiteSpace(Task.ExternalId); } } public string GitHubSourceText { get { return IsGitHubTask ? "GitHub · #" + Task.ExternalId : ""; } } public bool CanOpenGitHub { get { Uri uri; return IsGitHubTask && Uri.TryCreate(Task.ExternalUrl, UriKind.Absolute, out uri) && uri.Scheme == Uri.UriSchemeHttps && string.Equals(uri.Host, "github.com", StringComparison.OrdinalIgnoreCase); } } public string StatusText { get { return Task == null ? "" : Task.StatusText; } } public string DueText { get { return Task == null || !Task.DueDate.HasValue ? "No due date" : "Due " + Task.DueDate.Value.ToString("yyyy.MM.dd"); } } public string CompletedText { get { return Task != null && Task.CompletedAt.HasValue ? "Completed " + Task.CompletedAt.Value.ToString("yyyy.MM.dd HH:mm") : ""; } }
        public string NoteText { get { return noteText; } set { if (SetProperty(ref noteText, value)) System.Windows.Input.CommandManager.InvalidateRequerySuggested(); } } public string BlockReason { get { return blockReason; } set { if (SetProperty(ref blockReason, value)) System.Windows.Input.CommandManager.InvalidateRequerySuggested(); } } public string ErrorMessage { get { return errorMessage; } private set { SetProperty(ref errorMessage, value); } } public bool IsEditing { get { return isEditing; } set { SetProperty(ref isEditing, value); } }
        public bool IsCreatingGitHubIssue { get { return isCreatingGitHubIssue; } private set { if (SetProperty(ref isCreatingGitHubIssue, value)) { OnPropertyChanged("CanCreateGitHubIssue"); CommandManager.InvalidateRequerySuggested(); } } } public bool CanCreateGitHubIssue { get { return Task != null && !IsGitHubTask && !IsCreatingGitHubIssue && GitHubCreationService != null; } } public string GitHubMessage { get { return githubMessage; } private set { SetProperty(ref githubMessage, value); } } public ICommand CreateGitHubIssueCommand { get { return new RelayCommand(async p => await CreateGitHubIssueAsync(), p => CanCreateGitHubIssue); } }
        public string GitHubSyncText { get { if (!IsGitHubTask) return ""; if (Task.GitHubSyncStatus == GitHubSyncStatus.Pending || Task.GitHubSyncStatus == GitHubSyncStatus.Failed) return "⚠ Sync Pending"; if (Task.GitHubSyncStatus == GitHubSyncStatus.Syncing) return "◌ Syncing..."; return "● Synced"; } } public string GitHubSyncError { get { return Task == null ? "" : Task.LastGitHubSyncError; } } public bool HasPendingGitHubSync { get { return IsGitHubTask && (Task.GitHubSyncStatus == GitHubSyncStatus.Pending || Task.GitHubSyncStatus == GitHubSyncStatus.Failed); } } public bool IsSyncingGitHub { get { return isSyncingGitHub; } private set { if (SetProperty(ref isSyncingGitHub, value)) CommandManager.InvalidateRequerySuggested(); } } public ICommand RetryGitHubSyncCommand { get { return new RelayCommand(async p => await RetryGitHubSyncAsync(), p => HasPendingGitHubSync && !IsSyncingGitHub && GitHubSyncService != null); } }
        public string GitHubProjectSyncText { get { if (!IsGitHubTask) return ""; return Task.GitHubProjectSyncStatus == GitHubSyncStatus.Pending || Task.GitHubProjectSyncStatus == GitHubSyncStatus.Failed ? "Project   ⚠ Pending" : Task.GitHubProjectSyncStatus == GitHubSyncStatus.Syncing ? "Project   ◌ Syncing" : Task.GitHubProjectSyncStatus == GitHubSyncStatus.Synced ? "Project   ● Synced" : "Project   ○ Not configured"; } } public ICommand RetryAllGitHubCommand { get { return new RelayCommand(async p => await RetryGitHubSyncAsync(), p => IsGitHubTask && !IsSyncingGitHub && GitHubSyncService != null); } }
        public ICommand BackCommand { get; private set; } public ICommand AddNoteCommand { get; private set; } public ICommand StartCommand { get; private set; } public ICommand CompleteCommand { get; private set; } public ICommand BlockCommand { get; private set; } public ICommand UnblockCommand { get; private set; } public ICommand TodoCommand { get; private set; } public ICommand ToggleEditCommand { get; private set; } public ICommand SaveCommand { get; private set; } public ICommand OpenTaskCommand { get; private set; } public ICommand OpenParentCommand { get; private set; } public ICommand OpenGitHubCommand { get; private set; }
        public async System.Threading.Tasks.Task LoadAsync() { Task = await tasks.GetByIdAsync(taskId); if (Task == null) { ErrorMessage = "업무를 찾을 수 없습니다."; return; } BlockReason = Task.BlockedReason; ParentTask = Task.ParentTaskId.HasValue ? await tasks.GetByIdAsync(Task.ParentTaskId.Value) : null; var all = await tasks.GetAllAsync(); FollowUps.Clear(); foreach (WorkTask child in all.Where(x => x.ParentTaskId == Task.Id)) FollowUps.Add(child); var history = await tasks.GetHistoryAsync(Task.Id); Timeline.Clear(); DateTime? date = null; foreach (TaskHistory item in history.OrderBy(x => x.CreatedAt)) { bool show = !date.HasValue || date.Value.Date != item.CreatedAt.Date; Timeline.Add(new TimelineItemViewModel { History = item, ShowDate = show }); date = item.CreatedAt; } OnPropertyChanged("HasHistory"); RelatedMessages.Clear(); foreach (Message message in await conversations.GetRelatedMessagesAsync(Task.Id)) RelatedMessages.Add(message); }
        private async void Initialize() { await LoadAsync(); }
        private async System.Threading.Tasks.Task AddNoteAsync() { await tasks.AddMemoAsync(Task, NoteText.Trim()); NoteText = ""; await LoadAsync(); }
        private async System.Threading.Tasks.Task ChangeAsync(Func<System.Threading.Tasks.Task> action) { try { ErrorMessage = null; await action(); await LoadAsync(); } catch (Exception ex) { ErrorMessage = ex.Message; } }
        private async System.Threading.Tasks.Task SaveAsync() { try { StringBuilder memo = new StringBuilder("업무 정보 수정"); await tasks.UpdateAsync(Task, memo.ToString()); IsEditing = false; await LoadAsync(); } catch (Exception ex) { ErrorMessage = ex.Message; } }
        private async System.Threading.Tasks.Task CreateGitHubIssueAsync() { if (!CanCreateGitHubIssue) return; IsCreatingGitHubIssue = true; GitHubMessage = "Creating GitHub Issue..."; try { GitHubTaskCreationResult result = await GitHubCreationService.CreateForTaskAsync(Task, System.Threading.CancellationToken.None); GitHubMessage = result.Message; await LoadAsync(); } catch (Exception ex) { GitHubMessage = "GitHub Issue creation failed. Local task is still available. " + ex.Message; } finally { IsCreatingGitHubIssue = false; } }
        private async System.Threading.Tasks.Task RetryGitHubSyncAsync() { if (GitHubSyncService == null || Task == null) return; IsSyncingGitHub = true; try { await GitHubSyncService.RetryTaskAsync(Task); await LoadAsync(); } catch (Exception ex) { ErrorMessage = ex.Message; } finally { IsSyncingGitHub = false; } }
        private void OpenGitHub() { if (!CanOpenGitHub) return; try { System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(Task.ExternalUrl) { UseShellExecute = true }); } catch { ErrorMessage = "Could not open GitHub."; } }
        private void NotifyTask() { OnPropertyChanged("IsBlocked"); OnPropertyChanged("IsGitHubTask"); OnPropertyChanged("GitHubSourceText"); OnPropertyChanged("CanOpenGitHub"); OnPropertyChanged("CanCreateGitHubIssue"); OnPropertyChanged("GitHubSyncText"); OnPropertyChanged("GitHubProjectSyncText"); OnPropertyChanged("GitHubSyncError"); OnPropertyChanged("HasPendingGitHubSync"); OnPropertyChanged("StatusText"); OnPropertyChanged("DueText"); OnPropertyChanged("CompletedText"); CommandManager.InvalidateRequerySuggested(); }
    }
}
